Lightprotocol/light-protocol

.github/workflows/release.yml, .gitmodules
These BPF objects are going to be used in development environments for PSPs (Private Solana Programs).
=> ci: Add a Github workflow for building and releasing *.so files

cli/src/commands/init.ts, cli/src/utils/buildPSP.ts, cli/src/utils/downloadBin.ts, cli/yarn.lock
First of all, make it simplier by removing the maps and building URLs just with string concatenation. Simplier to read and less error-prone.
The original issue was that we were fetching light-anchor-linux-arm64 on macos-arm64 platforms (and vice versa), due to a typo in the map.
=> cli: Fix the download mechanism

README.md
* Fix the link to the image.
* Make the description less biased towards VS Code, just list IDEs and editors supporting devcontainers.
=> readme: Update information about Development Containers

cli/package.json
Binaries should be downloaded by each user for their system and architecture. We publish NPM packages from Linux x86_64 hosts usually, so publishing bin/ in the package usually results in shipping that binary to all users. That's a parial reason why it didn't work on macOS arm64.
=> cli: Do not inclue `bin/` folder, bump the version to 0.1.1-alpha.12

light-zk.js/src/utils.ts
Problem:
- balance fetch does not categorize spent utxos in all cases
- ci tests fail and seem flaky
Solution:
- force nullifier serialization during nullifier pubkey derivation to always be 32 bytes
=> zk-js: utils - fetchNullifierAccountInfo - fixes getBalance

light-account-compression/Cargo.lock, light-account-compression/Cargo.toml, light-system-programs/Cargo.lock, light-system-programs/Cargo.toml, light-system-programs/programs/merkle_tree_program/Cargo.toml, light-system-programs/programs/merkle_tree_program/src/message_merkle_tree/initialize.rs, light-system-programs/programs/merkle_tree_program/src/transaction_merkle_tree/initialize_new_merkle_tree_18.rs, light-system-programs/programs/merkle_tree_program/src/transaction_merkle_tree/update_merkle_tree_lib/merkle_tree_update_state.rs, light-system-programs/programs/merkle_tree_program/src/verifier_invoked_instructions/insert_nullifier.rs, light-system-programs/programs/merkle_tree_program/src/verifier_invoked_instructions/insert_two_leaves_message.rs, light-system-programs/programs/merkle_tree_program/src/verifier_invoked_instructions/insert_two_leaves_transaction.rs, light-system-programs/programs/merkle_tree_program/src/verifier_invoked_instructions/sol_transfer.rs, light-system-programs/programs/merkle_tree_program/src/verifier_invoked_instructions/spl_transfer.rs, light-system-programs/programs/verifier_program_one/Cargo.toml, light-system-programs/programs/verifier_program_one/src/lib.rs, light-system-programs/programs/verifier_program_storage/Cargo.toml, light-system-programs/programs/verifier_program_storage/src/lib.rs, light-system-programs/programs/verifier_program_two/Cargo.toml, light-system-programs/programs/verifier_program_two/src/lib.rs, light-system-programs/programs/verifier_program_zero/Cargo.toml, light-system-programs/programs/verifier_program_zero/src/lib.rs, light-verifier-sdk/Cargo.lock, light-verifier-sdk/Cargo.toml, light-verifier-sdk/src/state.rs, mock-app-verifier/Cargo.lock, mock-app-verifier/Cargo.toml, mock-app-verifier/programs/verifier/Cargo.toml
The newest solana-program crate was pulled unintentionally anyway which resulted in unexpected errors due to incompatibility of dependencies. More context: coral-xyz/anchor#2512
=> Update Solana SDK to 1.16 and Anchor to the latest change including it

light-system-programs/programs/merkle_tree_program/src/lib.rs, light-system-programs/programs/merkle_tree_program/src/transaction_merkle_tree/update_merkle_tree_lib/instructions_poseidon.rs, light-system-programs/programs/verifier_program_one/src/lib.rs, light-system-programs/programs/verifier_program_two/src/lib.rs
Fix Rust compiler warnings about:
* Redundant parenthesis.
* Redundant imports (`use something::` after `pub use::something::*`).
=> chore: Fix rustc warnings

.github/workflows/lint.yml, .github/workflows/test.yml
* Remove the usage of PAT_TOKEN in the checkout job - we don't have any private submodules, so there is no need for that.
* Push cache devcontainer image only when pull request is not coming from a fork.
=> CI: Make sure PAT_TOKEN is not used on pull requests from fork

light-system-programs/tests/user_tests.ts, light-zk.js/src/test-utils/testRelayer.ts, light-zk.js/src/test-utils/updateMerkleTree.ts, relayer/src/services/merkleTreeService.ts
this pr builds on  https://github.com/Lightprotocol/light-protocol/pull/143 and should be merged after
Problem:
- one anchor provider cannot be used to instantiate a merkle tree twice because it will send the same transactions again
- in case of the compute transactions the exact same transaction since the different data is just saved in the temporary account
Solution:
- instantiate a new connection and provider when updating the Merkle tree with the test relayer
- changed the user_test to test the new changes by only instantiating the provider and user once
Comment:
- this is somewhat a quick fix, we should think about a better solution maybe change the Merkle tree program to make transactions unique
=> zk.js: make provider reusable

light-zk.js/tests/account.test.ts
Problem:
- account test functional: aes encryption relies on the assumption that the decryption of an aes cipher text with an invalid secret key throws an error
- In most cases this assumption is correct. However, in some cases the library does not throw an error and just returns a value. This value is of course not the correct clear text since we are using an invalid secret key but the test fails because it expected an error.
Solution:
- add an additional check which asserts the incorrectness of the decrypted value should the decryption not throw an error
=> zk.js test: fixed flakyness in aes encryption test

light-zk.js/src/merkleTree/merkleTreeUpdater.ts, light-zk.js/src/test-utils/createAccounts.ts, light-zk.js/src/test-utils/initLookUpTable.ts, light-zk.js/src/transaction/sendVersionedTransaction.ts, light-zk.js/src/utils.ts
Problem:
- sometimes ci tests fail for transaction confirm timeout
- cause could be the use of deprecated the deprecated sendTransction method
Solution:
- replaced deprecated method calls
=> zk.js: remove deprecated sendTransaction method

light-system-programs/programs/merkle_tree_program/src/transaction_merkle_tree/update_merkle_tree_lib/instructions.rs, light-system-programs/programs/merkle_tree_program/src/transaction_merkle_tree/update_merkle_tree_lib/instructions_poseidon.rs
Problem:
- https://github.com/Lightprotocol/light-protocol/actions/runs/5281318114/jobs/9554721727?pr=145 ci tests failed because it ran out of compute units during merkle tree update
Solution:
- removed logs, which is lowest hanging fruit to save compute units
=> merkle tree program - merkle tree update: removed logs

light-system-programs/tests/user_tests.ts, light-zk.js/src/constants.ts, light-zk.js/src/relayer.ts, light-zk.js/src/test-utils/airdrop.ts, light-zk.js/src/test-utils/testStateValidator.ts, light-zk.js/src/transaction/transaction.ts, light-zk.js/src/wallet/provider.ts, light-zk.js/src/wallet/user.ts, light-zk.js/tests/relayer.test.ts, relayer/tests/functional_test.ts
Problem:
- unshield recipient arguments were confusing
Solution:
- take a recipient sol account and use the associated token account as destination for the spl unshield
=> zk.js: user - unshield unified sol and spl recipient

light-system-programs/tests/merkle_tree_tests.ts, light-zk.js/src/merkleTree/merkleTreeUpdater.ts
Problem:
- merkle tree update is still flaky
Solution Attempt:
- did not crash during a 6h test in ci so hopefully this is a sustainable solution
- refactored merkle tree update compute instruction execution function
- send 28 transactions (the exact amount of transactions to update the Merkle tree when inserting 1 pair of leaves)
- check whether Merkle tree update is complete
- if not send another 10 transactions
- the update might not be complete after 28 transactions because it is a batched update the update (for more insertions we need to compute more hashes -> more transactions) or transactions failed
- if a limit of 120 transactions is reached an error is thrown
=> zk.js: merkle tree update added retry logic

light-system-programs/runTest.sh, light-system-programs/runTestNoAccounts.sh, mock-app-verifier/runTest.sh, relayer/runTest.sh
Docker on macOS doesn't support the `--net=host` option. And using it is a bad practice anyway. Instead of doing that, map all the ports that solana-test-validator listens to directly to the host.
=> tests: Fix connection to validator container on macOS hosts

light-zk.js/src/utils.ts, light-zk.js/src/utxo.ts
Problem:
- ethereum-crypto environment detection is not reliable
Solution:
- detect the environment differently and set env variables such that ethereum-crypto detects the env correctly
- add utils function which sets the crypto variables correctly
- set env in utxo.encrypt and utxo.decrypt
Note:
- this is not tested for a browser env
- let's merge it anyway but keep this in mind
Error:
```
TypeError: Cannot read properties of undefined (reading 'importKey')
at getBrowserKey (node_modules/@lightprotocol/zk.js/node_modules/ethereum-cryptography/aes.js:33:42)
at encrypt (node_modules/@lightprotocol/zk.js/node_modules/ethereum-cryptography/aes.js:41:36)
at Utxo.<anonymous> (node_modules/@lightprotocol/zk.js/src/utxo.ts:615:39)
at [Generator.next](http://generator.next/) (<anonymous>)
at …
```
=> zk.js - utxo encryption & decryption: set env correctly for aes

light-system-programs/tests/user_tests.ts, light-zk.js/src/relayer.ts, light-zk.js/src/wallet/provider.ts
Problem:
- with every provider instantiation a new lookup table is created regardless whether the lookuptable of the relayer already exists
Solution:
- refactored provider's fetchLookUpTable  method to check whether the lookuptable already exists
=> zk.js: fix reinstantiating lookuptable

light-system-programs/tests/user_tests.ts, light-system-programs/tests/verifier_tests.ts, light-zk.js/src/merkleTree/solMerkleTree.ts, light-zk.js/src/relayer.ts, light-zk.js/src/test-utils/airdrop.ts, light-zk.js/src/test-utils/testRelayer.ts, light-zk.js/src/test-utils/testStateValidator.ts, light-zk.js/src/test-utils/testTransaction.ts, light-zk.js/src/transaction/sendVersionedTransaction.ts, light-zk.js/src/transaction/transaction.ts, light-zk.js/src/transaction/transactionParameters.ts, light-zk.js/src/wallet/buildBalance.ts, light-zk.js/src/wallet/selectInUtxos.ts, light-zk.js/src/wallet/user.ts, light-zk.js/tests/balance.test.ts, mock-app-verifier/tests/functional_test.ts, relayer/runScript.sh, relayer/src/index.ts, relayer/src/services/transactionService.ts, relayer/tests/functional_test.ts
Problem:
- user shield/transfer/unshield wait for merkle tree to update which takes a couple seconds while the transaction is already finalized
Solution:
- add two confirm options:
- finalized (utxos are spend and new utxos are queued but not inserted into the merkle tree yet)
-> transaction is final but new utxos are not spendable yet
- spendable (utxos are spent and new utxos are spendable -> have been inserted into the merkle tree)
=> zk.js: added confirm options

light-system-programs/tests/functional_tests.ts, light-system-programs/tests/merkle_tree_tests.ts, light-system-programs/tests/provider.test.ts, light-system-programs/tests/user_tests.ts, light-system-programs/tests/verifier_tests.ts, light-zk.js/src/account.ts, light-zk.js/src/test-utils/functionalCircuit.ts, light-zk.js/src/test-utils/testStateValidator.ts, light-zk.js/src/test-utils/testTransaction.ts, light-zk.js/src/transaction/transactionParameters.ts, light-zk.js/src/utxo.ts, light-zk.js/src/wallet/buildBalance.ts, light-zk.js/src/wallet/user.ts, light-zk.js/tests/balance.test.ts, light-zk.js/tests/circuits.test.ts, light-zk.js/tests/prover.test.ts, light-zk.js/tests/transaction.test.ts, light-zk.js/tests/transactionParameters.test.ts, light-zk.js/tests/utxo.test.ts, mock-app-verifier/tests/functional_test.ts, mock-app-verifier/tests/verifier_tests.ts
Problem:
- transaction nonce as domain separator is unreliable because it is easy to produce situations in which the transaction nonce is not up to date
Solution:
- changed domain separator from transaction nonce to commitment hash
- removed transaction nonces completely
Note:
- this will be revisited when benchmarking performance of encryption
- we should also evaluate whether we want to switch from blake2b to a hdkf
=> zk.js - utxo encryption

light-zk.js/src/wallet/user.ts
Problem:
- unshielding to a sol address which already has an initialized associated token account fails because it always tries to create a new token account
Solution:
- fix detection whether an associated token account already exists, thus don't try to create one when it already exists
=> zk.js - user - unshield: fixed associated token account creation

README.md, cli/scripts/runTest.sh, light-circuits/buildCircuit.sh, light-system-programs/scripts/runTest.sh, light-system-programs/scripts/runTestNoAccounts.sh, mock-app-verifier/runTest.sh, mock-app-verifier/scripts/buildCircuit.sh, relayer/runScript.sh, relayer/runTest.sh, scripts/build.sh, scripts/devenv.sh, scripts/getAccountState.sh, scripts/install.sh, scripts/lint.sh, scripts/test.sh
Since we have a reliable devenv which doesn't require containerization, stop using docker in `yarn *test*` commands.
This change doesn't impact devcontainer. It's affects only running tests on host systems, where Docker is not required anymore.
=> tests: Run without Docker

light-system-programs/tests/functional_tests.ts, light-system-programs/tests/merkle_tree_tests.ts, light-system-programs/tests/provider.test.ts, light-system-programs/tests/user-merge-sol-specific.tests.ts, light-system-programs/tests/user-merge-sol.tests.ts, light-system-programs/tests/user-merge-spl-specific.tests.ts, light-system-programs/tests/user-merge-spl.tests.ts, light-system-programs/tests/user-merge.tests.ts, light-system-programs/tests/user-random.tests.ts, light-system-programs/tests/user_tests.ts, light-system-programs/tests/verifier_tests.ts, light-verifier-sdk/Cargo.lock, light-zk.js/src/test-utils/airdrop.ts, light-zk.js/src/test-utils/testRelayer.ts, light-zk.js/src/transaction/sendVersionedTransaction.ts, mock-app-verifier/tests/functional_test.ts
Problem:
- if payer was not provided a payer was generated and relayer pubkey and payer did not match
- error propagation in sendVersionedTransaction was broken
=> zk.js TestRelayer: make payer mandatory

scripts/install.sh
`local` declaration is not in POSIX standard and is not supported by dash (which is the Bourne sh implementation used on Ubuntu). Variables declared in our functions don't override anything global, so there is no risk breaking anything.
=> scripts: Make ìnstall.sh working on dash shell

.github/workflows/release.yml
Use devenv and re-use the build action instead of installing dependencies manually.
=> ci: Fix the release job

.github/workflows/release.yml
Problem:
Release with prior fix pr did not public release binaries [see release](https://github.com/Lightprotocol/light-protocol/releases/tag/v0.3.1) 
Changes:
- adjust path to which binaries are copied so that the release action finds them
- added spl_noop.so binary
=> github action - release: fix cp paths, include spl_noop.so

.github/workflows/pr.yml
This action makes sure that all pull requests are following the Conventional Commits specification[0], which can be summarized as:
```
<type>([optional scope]): <description>
```
Where types are: `fix`, `feat`, `build`, `chore`, `ci`, `docs`, `style`, `refactor`, `perf` and `test`.
For this repository, configure it with following scopes:
* `programs` - on-chain programs (verifiers, Merkle tree programs).
* `verifier-sdk` - SDK for on-chain verifier programs.
* `circuits` - arithmetic circuits.
* `light-zk.js` - client SDK.
* `cli`
* `relayer`
* `scripts`
For example, these PR titles are valid:
* feat: Add support of multiple Merkle trees
* feat(cli): Add `shield` command
* fix: Ensure consinstency of integrity hash inputs
* chore: Update Anchor version to 0.29.0
* refactor(program): Avoid …
=> ci: Add action-semantic-pull-request for linting pull requests

light-system-programs/programs/merkle_tree_program/src/verifier_invoked_instructions/insert_two_leaves_event.rs, light-verifier-sdk/src/cpi_instructions.rs, light-verifier-sdk/src/light_transaction.rs, light-zk.js/src/idls/merkle_tree_program.ts
These fields are securing that instruction, making sure that it's called via CPI from a registered verifier program.
=> fix(programs): Require signer and registered verifier in `insert_two_leaves_event` instruction

.github/actions/setup-and-build/action.yml, .github/workflows/light-sdk-tests.yml
adds  cache for rust and node dependencies
rust: (cargo/registry cargo/git, target) 
node: (node_modules)
and generates hashkeys to check for deps changes as per https://buildjet.com/for-github-actions/docs/guides/migrating-to-buildjet-cache
=> ci: cache node rust

cli/yarn.lock, light-prover.js/src/prover.ts, light-prover.js/tests/prover.test.ts, light-zk.js/src/transaction/transaction.ts
1. Fixed hanging prover by removing [curve_bn128 termination](https://github.com/Lightprotocol/light-protocol/compare/sergey/fix-hanging-prover?expand=1#diff-c1e3f2eb68f44e0a5a7e85e7aa4bbf296418ef7d00636c20e488804149c2e676L127-L133). It is still needed for testing, so I moved it there.
2. Added [detailed log output](https://github.com/Lightprotocol/light-protocol/compare/sergey/fix-hanging-prover?expand=1#diff-513f716441a59b00a665381cba435672a3855b01635e3e266dd46f7fee5a4becR375-R376) about proving instead of the well-known "Proof generation + Parsing". This change adds transparency to the understanding of what's going on inside of the prover and eliminates warnings: 
> Warning: Label 'Proof generation + Parsing' already exists for console.time()
=> fix: hanging prover + add detailed prover log output

light-verifier-sdk/src/light_transaction.rs
`self.mint_pubkey` is set as follows:
```rust
self.mint_pubkey = [
vec![0u8],
hash(&sender_mint.mint.to_bytes()).try_to_vec()?[1..].to_vec(),
];
```
So the removed condition check (whether `self.mint_pubkey[1..]` is not equal to `hash(&sender_mint.mint.to_bytes())[1..]` can be never true. It's redundant.
Fixes: #238
=> fix(verifier-sdk): Remove redundant comparison of mint public key

light-system-programs/tests/functional_tests.ts, light-system-programs/tests/user-random.tests.ts, light-system-programs/tests/user.tests.ts, light-system-programs/tests/verifier_tests.ts, light-zk.js/src/account.ts, light-zk.js/src/constants.ts, light-zk.js/src/relayer.ts, light-zk.js/src/test-utils/createAccounts.ts, light-zk.js/src/test-utils/testChecks.ts, light-zk.js/src/test-utils/testRelayer.ts, light-zk.js/src/test-utils/userTestAssertHelper.ts, light-zk.js/src/transaction/fetchRecentTransactions.ts, light-zk.js/src/transaction/transaction.ts, light-zk.js/src/transaction/transactionParameters.ts, light-zk.js/src/utils.ts, light-zk.js/src/utxo.ts, light-zk.js/src/wallet/buildBalance.ts, light-zk.js/src/wallet/createOutUtxos.ts, light-zk.js/src/wallet/selectInUtxos.ts, light-zk.js/src/wallet/user.ts, light-zk.js/tests/balance.test.ts, light-zk.js/tests/circuits.test.ts, light-zk.js/tests/convertDecimals.test.ts, light-zk.js/tests/createOutUtxos.test.ts, light-zk.js/tests/relayer.test.ts, light-zk.js/tests/selectInUtxos.test.ts, light-zk.js/tests/transaction.test.ts, light-zk.js/tests/transactionParameters.test.ts, light-zk.js/tests/utxo.test.ts
* Define often used big numbers (0, 1, 2) as constants, exported in light-zk.js as a whole.
* Avoid conversion to strings when comparing big numbers, favor using `.eq()` instead. Sadly, `===` is not reliable in this case.
=> refactor(light-zk.js): Avoid allocations and string operations when using `BN`

cli/src/psp-utils/constants.ts
The change with `#[light_verifier_accounts]` macro (#232) is already merged, so it's time to use the main branch of Light Protocol in the PSP template.
=> chore(cli): Switch to the main branch of Light Protocol

cli/src/commands/merkle-tree/initialize.ts, cli/test/commands/merkle-tree/index.test.ts
* Mention "Merkle Trees" instead of "Transaction Merkle Tree". This command initialized the pair of trees (transaction and event) at once.
* Make indexes and public keys human-readable.
=> fix(cli): Correct the output of `merkle-tree:initialize` command

cli/src/commands/asset-pool/list.ts, cli/src/commands/asset-pool/register-spl.ts, cli/src/commands/pool-type/list.ts, cli/src/commands/pool-type/register.ts, cli/test/commands/asset-pool/index.test.ts, cli/test/commands/pool-type/index.test.ts
Previously we were able to only list pool types. This command allows to register them as well.
Also, fix the `asset-pool:register-sol` and `asset-pool:register-spl` subcommands to take pool type (as big number) as a required argument.
=> feat(cli): Add `pool-type:register` command

cli/scripts/copyLocalProgramBinaries.sh, cli/src/utils/initTestEnv.ts, light-system-programs/Cargo.lock, light-system-programs/package.json, light-system-programs/programs/user_registry/Cargo.toml, light-system-programs/programs/user_registry/Xargo.toml, light-system-programs/programs/user_registry/src/lib.rs, light-system-programs/tests/user-registry.tests.ts, light-zk.js/src/constants.ts, light-zk.js/src/idls/index.ts, light-zk.js/src/idls/user_registry.ts
This registry is the on-chain program where Solana users are supposed to store their Light Protocol public keys. Then this program and its accounts should be used by the SDK for resolution.
=> feat(programs): Add User Registry mapping Solana to Light Protocol accounts

scripts/devenv.sh
To make sure that `light` command always points to the locally built CLI, instead of any globally installed command, and to get rid of necessity of typing `./cli/test_bin/run` manually, define an alias.
=> build: Define alias for `light` command in devenv

.github/workflows/light-sdk-tests.yml, circuit-lib/circuit-lib.circom/package.json
Problem:
- scripts/test.sh is rebuilding circuits but we do not want to commit new proving keys with every pr
Solution:
- just execute yarn test-build-light-circuits (in circuit-lib.circom) in ci
=> refactor: circuit-lib.circom - execute test-build-light-circuits only in ci

relayer/src/services/indexerService/indexer.ts, relayer/src/services/indexerService/runIndexer.ts, relayer/src/services/indexerService/search.ts, relayer/src/services/transactionService.ts, scripts/test.sh, zk.js/src/test-utils/testRelayer.ts, zk.js/src/test-utils/testTransaction.ts, zk.js/src/test-utils/userTestAssertHelper.ts, zk.js/src/transaction/fetchRecentTransactions.ts
problem
- fetchRecentTransactions applies several filters after its 'getConfirmedSignaturesForAddress2' call. if the oldest fetched signature gets filtered out i.e. is not a shielded tx, the last indexed shielded tx != lastfetched sig.
in that case the indexer would get stuck in an infinite loop where it would always find new sigs to fetch, resulting in tons of redundant calls (hundreds every couple of seconds)
fix:
- store the actual oldestFetchedSig  in the db. searchBackward now uses that sig instead of the sig of the oldest indexed tx.
results:
- each "index" round now only does 2 single rpc calls (1 forward, 1 backward) if no new transactions get added.
=> fix: prevent redundant indexer rounds (infinite loop bug)

zk.js/src/account.ts, zk.js/src/utxo.ts, zk.js/src/wallet/user.ts, zk.js/tests/account.test.ts, zk.js/tests/utxo.test.ts
- refactor encryption so that secrets do not leave the account class
- move nacl and aes encryption to account class
Account Aes Api:
- encryptAesUtxo (encrypts utxo bytes with utxo viewing key and iv from commitment)
- encryptAes (encrypts bytes with aes secret key, iv16 is optional and 16 random bytes by default, the iv is the first 16 bytes of the cipher text)
- _encryptAes (private aes encryption method which is used in encryptAes and encryptAesUtxo)
- decryptAesUtxo (decrypts encrypted utxo bytes with utxo viewing key and iv from commitment)
- decryptAes (decrypts aes encrypted bytes, the iv is expected to be the first 16 bytes)
- _decryptAes (private aes decryption method which is used in decryptAes and decryptAesUtxo)
Account Nacl Api:
(Encrypt operations do use a secret thus do …
=> refactor: move encryption to account

scripts/install.sh
… ensure compatibility with 'aarch64' systems alongside 'arch64' and 'arm64'.
=> chore: add aarch64 to install.sh

system-programs/tests/functional_tests.ts, system-programs/tests/merkle_tree_tests.ts, system-programs/tests/provider.test.ts, system-programs/tests/verifier_tests.ts, zk.js/src/account.ts, zk.js/src/test-utils/functionalCircuit.ts, zk.js/src/transaction/transaction.ts, zk.js/src/transaction/transactionParameters.ts, zk.js/src/utxo.ts, zk.js/src/wallet/user.ts, zk.js/tests/circuits.test.ts, zk.js/tests/prover.test.ts, zk.js/tests/transaction.test.ts, zk.js/tests/transactionParameters.test.ts
This pr is based on https://github.com/Lightprotocol/light-protocol/pull/275 please merge in sequence.
- secrets are necessary to generate light system proofs
- move proof gen into account class and add private key class internally so that secrets are not exposed
- move proof gen from transaction to account
- add addPrivateKey method to account.ts -> it can only add the private key of the account. This clashes with the way we so far added empty/filling utxos.
- add account as input to TransactionParameters so that filling utxos are all owned by the same account not random accounts
- add isFillingUtxo marker to Utxo
We don't want to decrypt a lot of random utxos therefore  if utxo is filling utxo make the prefix random, so that we don't decrypt  these utxos by default.
=> refactor: move proof gen to account

verifier-sdk/src/light_transaction.rs
Rename `recipient_spl` to `recipient_sol` and remove the unneeded comment.
=> fix(verifier-sdk): Correct the argument name in `deposit_sol`

verifier-sdk/src/light_transaction.rs
The latter is more accurate, since it's the only operation done there.
=> fix(verifier-sdk): Rename `check_inputs` to `check_remaining_accounts`

cli/config.json, cli/src/commands/config/config.ts, cli/src/psp-utils/constants.ts, cli/src/utils/utils.ts, relayer/src/index.ts, relayer/src/services/index.ts, relayer/src/services/infoService.ts, relayer/tests/functional_test.ts, relayer/tests/runTestCli.sh, zk.js/src/relayer.ts
Problem:
- relayerPubkey and relayerRecipientSol need to be configured manually
- inconsistencies cause transactions to fail
Changes:
- relayer server:
- add getRelayerInfo path to relayer server (returns current relayerPubkey, relayerRecipientSol, relayerFee, relayerFeeHigh)
- Relayer class zk.js
- added Relayer.initFromUrl and relayer.syncRelayerInfo(url: string) which does a request to getRelayerInfo()
- CLI:
- added config fields for relayerFee and highRelayerFee
- added syncRelayer flag to config command which syncs the relayer info
=> feat(relayer): added getRelayerInfo

DOCUMENTATION_v3.md, cli/src/commands/merkle-tree-authority/get.ts, system-programs/programs/merkle_tree_program/src/config_accounts/merkle_tree_authority.rs, system-programs/programs/merkle_tree_program/src/lib.rs, system-programs/tests/merkle_tree_tests.ts, zk.js/src/idls/merkle_tree_program.ts, zk.js/src/merkleTree/merkleTreeConfig.ts
It wasn't used anywhere. We can treat uncompressed NFTs as regular SPL tokens. Supporting compressed NTFs is going to require an another approach.
=> chore: Remove `enable_nfts` configuration and instruction

zk.js/src/merkleTree/merkleTreeConfig.ts
Do so not only by checking if the account info is not null, but also by checking fields. That affects:
* Merkle Tree Authority
* Transaction Merkle Tree
* Event Merkle Tree
=> fix(zk.js): Ensure that Merkle Tree accounts are initialized

.github/actions/setup-and-build/action.yml
Node builds are not a bottleneck and caching them makes builds flaky. Let's disable caching of node modules and keep caching only Rust and third-party dependencies from install.sh.
=> chore: Do not cache node modules

system-programs/programs/merkle_tree_program/src/event_merkle_tree/initialize.rs, system-programs/programs/merkle_tree_program/src/lib.rs, system-programs/programs/merkle_tree_program/src/transaction_merkle_tree/initialize_new_merkle_tree_18.rs, system-programs/programs/merkle_tree_program/src/transaction_merkle_tree/state.rs, system-programs/programs/merkle_tree_program/src/transaction_merkle_tree/update_merkle_tree_lib/merkle_tree_update_state.rs, system-programs/programs/merkle_tree_program/src/transaction_merkle_tree/update_merkle_tree_lib/processor.rs, system-programs/programs/merkle_tree_program/src/utils/config.rs, system-programs/programs/merkle_tree_program/src/utils/constants.rs, zk.js/src/idls/merkle_tree_program.ts
Use it both for Transaction and Event Merkle Tree.
=> chore: Unify the `MERKLE_TREE_HEIGHT` constant

cli/src/psp-utils/constants.ts
Recently we renamed some crates, therefore breaking PSP template and building PSPs. Before we apply necessary changes in the template, let's pin the monorepo dependency to the commit before breaking changes.
=> chore(cli): Point PSP template to the commit that it's compatible with

programs/merkle-tree/Cargo.toml, programs/psp10in2out/Cargo.toml, programs/psp2in2out-storage/Cargo.toml, programs/psp2in2out/Cargo.toml, programs/psp4in4out-app-storage/Cargo.toml
That's required in order to avoid errors like this one:
https://github.com/Lightprotocol/light-protocol/actions/runs/6532753325/job/17736550803
=> chore: Specify versions of local crates which are published on crates.io

.github/workflows/light-sdk-tests.yml, .github/workflows/light-system-programs-tests.yml, .github/workflows/lint.yml
- switched ci runner to ubuntu-latest
- removed zk.js from sdk ci tests, it was slowing ci down by a lot because it also executes system program tests since those were moved to zk.js
- moved zk.js to system program merge tests
- moved relayer tests to circuit tests to rebalance
=> chore: ci - switch runner to ubuntu-latest, remove zk.js

.github/workflows/release-macro-circom.yml, .github/workflows/release.yml
The one which we used in the Lightprotocol/macro-circom repo.
=> fix: Use the old workflow for building macro-circom

web/webapp/copy-circuits.sh, web/webapp/package.json, web/webapp/testSetup.sh
- running pnpm serve / build manually fails if the build-circuits folder isn't placed in the public folder prior. 
fix:
- extract it from the` testsetup.sh` script into its own` copy-circuits.sh` script and add it as its own prebuild step
=> chore: extract copy-circuits.sh into prebuild step

zk.js/src/merkleTree/merkleTreeUpdater.ts, zk.js/src/test-utils/updateMerkleTree.ts
When Poseidon syscall is used and transactions are atomic, leaves PDAs are not created on purpose.
=> fix(zk.js): Don't check `leavesPdas` when atomic transactions are enabled

.github/actions/setup-and-build/action.yml, psp-examples/private-compressed-account/Cargo.lock, psp-examples/rock-paper-scissors/Cargo.lock, psp-examples/streaming-payments/Cargo.lock, psp-examples/swap/Cargo.lock, relayer/tests/browser_test.ts, relayer/tests/functional_test.ts, relayer/tests/runTestCli.sh, scripts/install.sh, scripts/test-atomic-tx.sh, scripts/test-no-atomic-tx.sh
pnpm is not aware of Rust features and there is no sane way to tell pnpm or nx to rebuild program without "atomic-transactions" feature.
However, we can try to distinguish the caches.
=> ci: Distinguish between caches with and without atomic transactions

nx.json
Ignore nx on LIGHT_PROTOCOL_ATOMIC_TRANSACTIONS env change.
https://nx.dev/recipes/running-tasks/customizing-inputs#include-environment-variables-in-cache-hash
=> chore: Add "LIGHT_PROTOCOL_ATOMIC_TRANSACTIONS" to build inputs in nx.json.

.gitignore, web/webapp/copy-circuits.sh
• webapp expect existence of `public/build-circuits/` path. If we enable -R flag for `cp`, and source_file for `cp` ends in a /, the contents of the directory are copied rather than the directory itself. This is not what we expect. 
• .gitignore updated, /web/webapp/public/build-circuits included.
=> fix: update source path in copy-circuits.sh

pnpm-lock.yaml, psp-examples/multisig/README.md, psp-examples/multisig/package.json, psp-examples/private-compressed-account/README.md, psp-examples/private-compressed-account/package.json, psp-examples/rock-paper-scissors/README.md, psp-examples/rock-paper-scissors/package.json
- Some psp examples (multisig, private-compressed-account, rock-paper-scissors) are not maintained and tested are excluded from ci.
- Since these psps are part of the pnpm workspace we still build them, which takes a lot of time.
- remove package.json scripts of unmaintained psp examples
=> refactor: removed scripts of unmaintained psps

psp-examples/streaming-payments/Cargo.lock, psp-examples/swap/Cargo.lock, zk.js/src/account.ts, zk.js/src/utxo.ts, zk.js/src/wallet/buildBalance.ts, zk.js/src/wallet/user.ts, zk.js/tests/account.test.ts, zk.js/tests/balance.test.ts, zk.js/tests/utxo.test.ts
- for rpc refactor we need to be able to compute prefixes without knowledge of the commitment hash of a utxo
- account.ts
- add prefixCounter - to keep track of the latest derived prefix hash
- remove commitment hash from prefix hash derivation
- add merkle tree public key to prefix hash derivation
- utxo.ts
- remove prefix check and checked decryption
- replace decrypt with decryptUnchecked
=> refactor(zk.js): account - prefix hash derivation

.github/actions/setup-and-build/action.yml, pnpm-lock.yaml, zk.js/src/idls/light_psp2in2out.ts
If there are any dirty, uncommited changes after build, it means that some autogenerated file (IDL, lock files of Cargo or pnpm etc.) was not commited, even though it should've been. Detect such changes in CI.
=> ci: Detect uncommited changes after build

.github/workflows/lint.yml, programs/merkle-tree/src/config_accounts/merkle_tree_authority.rs, programs/merkle-tree/src/transaction_merkle_tree/update_merkle_tree_lib/instructions.rs, programs/merkle-tree/src/verifier_invoked_instructions/insert_two_leaves_transaction.rs, scripts/install.sh, scripts/lint.sh
Running clippy nightly is often necessary on macOS (thiserror[0] fails to build on Rust stable on macOS, we need to investigate why, it's not in the scope of this change).
But well, new features of clippy nightly are also pointing out some good coding practices, so we can also enable it anyway and just keep it.
[0] https://crates.io/crates/thiserror
=> ci: Run Rust liners both on stable and nightly toolchains

Cargo.lock, merkle-tree/reference/Cargo.toml, merkle-tree/reference/src/lib.rs, merkle-tree/reference/tests/tests.rs
It's going to be useful for testing and building off-chain MT instances in Rust.
It aims to be similar to spl-merkle-tree-reference[0], but the difference is that it supports multiple hash algorithms.
[0] https://crates.io/crates/spl-merkle-tree-reference
=> feat: Add reference Merkle tree implementation

Cargo.lock, account.rs/src/wasm/Cargo.toml, merkle-tree/concurrent/Cargo.toml, merkle-tree/concurrent/src/changelog.rs, merkle-tree/concurrent/src/hash.rs, merkle-tree/concurrent/src/lib.rs, merkle-tree/concurrent/tests/tests.rs, merkle-tree/hasher/src/errors.rs, merkle-tree/reference/src/lib.rs, merkle-tree/reference/tests/tests.rs, programs/merkle-tree/Cargo.toml, programs/psp10in2out/Cargo.toml, programs/psp2in2out-storage/Cargo.toml, programs/psp2in2out/Cargo.toml, programs/psp4in4out-app-storage/Cargo.toml, programs/user-registry/Cargo.toml, psp-examples/multisig/programs/multisig/Cargo.toml, psp-examples/private-compressed-account/programs/private-compressed-account/Cargo.toml, psp-examples/rock-paper-scissors/programs/rock-paper-scissors/Cargo.toml, psp-examples/streaming-payments/programs/streaming-payments/Cargo.toml, psp-examples/swap/programs/swaps/Cargo.toml, psp-template/psp-template/programs_circom/program_name/Cargo.toml, psp-template/psp-template/programs_psp/program_name/Cargo.toml
Concurrent Merkle tree is the concept of updateable MT which is described in the whitepaper[0] written by gigabrains from Solana Labs and Metaplex.
It allows for concurrent updates (of already inserted leaves) of the tree without any locks and queues.
Incorporating it into Light Protocol is a huge upgrade from our previous append-only sparse Merkle Tree implementations.
Although we don't need updates for transactions (append-only is sufficient there), we are going to need updates when imlementing indexed Merkle tree for nullifiers[1]. This feature is a preparatory change for implementing indexed Merkle tree.
[0] https://drive.google.com/file/d/1BOpa5OFmara50fTvL0VIVYjtg-qzHCVc/view
[1] https://docs.aztec.network/concepts/advanced/data_structures/indexed_merkle_tree
=> feat: Add concurrent Merkle tree

merkle-tree/concurrent/src/changelog.rs, merkle-tree/concurrent/src/hash.rs, merkle-tree/concurrent/src/lib.rs
* Stick to `HEIGHT` instead of `MAX_HEIGHT`.
* Make sure that variables containing "leaf" in name are actual leaves - in case of variables where upper nodes can be assigned, use "node".
=> style: Fix naming in the concurrent Merkle tree module

.github/workflows/pr.yml, merkle-tree/concurrent/src/changelog.rs, merkle-tree/concurrent/src/lib.rs, merkle-tree/concurrent/tests/tests.rs, merkle-tree/hasher/src/errors.rs
This change fixes couple of mistakes in the concurrent Merkle tree implementation, which resulted in the rightmost proofs being corrupt:
* The newest changelog entry was never used (iteration was done until `self.current_changelog_index`, adding `1` fixed that).
* We were not updating the rightmost proof on update operations affecting the non-rightmost leafs, even though they can affect the rightmost proof.
* We were returning an error when any changelog entry was affecting the currently updated leaf. That's a correct thing to do then updating proofs provided by the user. But in case of evaluating rightmost proofs, a correct thing to do is updating the rightmost leaf.
* After fixing the issues above, the proof update needed to be guarded by a check which skips it when the tree has no …
=> fix(merkle-tree): Update the rightmost proof and leaf correctly

psp-examples/private-compressed-account/tests/private-compressed-account.ts
cursor went ballistic and we dont run tests for the private-compressed-account PSP example, and I didn't catch it either.  we should consider kicking those untested ones out and into separate repos for until we're done with this wave of breaking changes.
=> chore: bring back private-compressed-account

Cargo.lock, macros/light/src/lib.rs, programs/psp10in2out/Cargo.toml, programs/psp10in2out/src/lib.rs, programs/psp2in2out-storage/Cargo.toml, programs/psp2in2out-storage/src/lib.rs, programs/psp2in2out/Cargo.toml, programs/psp2in2out/src/lib.rs, programs/psp4in4out-app-storage/Cargo.toml, programs/psp4in4out-app-storage/src/lib.rs, psp-examples/streaming-payments/Cargo.lock, psp-examples/streaming-payments/programs/streaming-payments/Cargo.toml, psp-examples/streaming-payments/programs/streaming-payments/src/lib.rs, psp-examples/streaming-payments/tests/streaming-payments.ts, psp-examples/swap/Cargo.lock, psp-examples/swap/programs/swaps/Cargo.toml, psp-template/psp-template/programs_psp/program_name/Cargo.toml, verifier-sdk/Cargo.toml, verifier-sdk/src/light_transaction.rs
Changes:
- add heap-neutral proc macro which frees all heap memory allocated during the use of a method at the end of the method
- the macro has a check that it can only be used with methods which do not modify it's struct
- however we still need to be careful with this
=> feat: add active heap management

.github/workflows/lint.yml, scripts/format.sh, scripts/install.sh, scripts/lint.sh
The newest Rust nightly removed the `stdsimd` feature in favor of more grained features (rust-lang/rust#117372).
However, the version of `ahash` we depend on, still requires that feature. New release of `ahash` (0.8.7) contains a fix, but we can't upgrade to it without upgrading Anchor.
Pinning Rust nightly seems to be the less intrusive solution for now.
=> ci: Pin Rust nightly to 2024-02-01

merkle-tree/concurrent/src/lib.rs
Because that's the only thing this function does - it updates the proof based on the new changelogs.
The confusion came from similarly named `update_proof_or_leaf` function in the SPL implementation and whitepaper, which returns a leaf when patching the changelog is impossible (because a new changelog entry affects the leaf we want to update). But we are not doing it - we found it confusing and we decided to handle that edge case by returning an error.
=> chore: Rename `update_proof_or_leaf` to `update_proof`

Cargo.lock, merkle-tree/concurrent/Cargo.toml, merkle-tree/concurrent/src/errors.rs, merkle-tree/concurrent/src/hash.rs, merkle-tree/concurrent/src/lib.rs, merkle-tree/concurrent/tests/tests.rs, merkle-tree/hasher/Cargo.toml, merkle-tree/hasher/src/errors.rs, merkle-tree/hasher/src/keccak.rs, merkle-tree/hasher/src/poseidon.rs, merkle-tree/hasher/src/sha256.rs, merkle-tree/hasher/src/syscalls/definitions.rs, merkle-tree/indexed/Cargo.toml, merkle-tree/indexed/src/array.rs, merkle-tree/indexed/src/errors.rs, merkle-tree/indexed/src/lib.rs, merkle-tree/indexed/src/reference.rs, merkle-tree/indexed/tests/tests.rs, programs/merkle-tree/Cargo.toml, programs/merkle-tree/src/state/merkle_tree_set.rs, programs/merkle-tree/src/verifier_invoked_instructions/insert_two_leaves_event.rs, programs/merkle-tree/src/verifier_invoked_instructions/insert_two_leaves_transaction.rs, zk.js/src/idls/psp_compressed_pda.ts, zk.js/src/idls/psp_compressed_token.ts
Use `thiserror` for error enums.
Introduce the `solana` feature which:
* Adds `solana-program` as a dependency.
* Makes it possible to convert the custom error types to `ProgramError`.
=> chore(merkle-tree): Make dependency on `solana-program` optional

scripts/format.sh, scripts/lint.sh
We are using rustfmt features which are not stabilized yet, but are convenient for us - precisely - import sorting.
Running rustfmt stable with these option triggers annoying warnings, which can often obfuscate actual errors. Therefore, let's run only rustfmt nightly.
=> ci: Run rustfmt with Rust nigthly

js/stateless.js/tests/e2e/program.test.ts, js/stateless.js/tests/e2e/transfer-emit-events.test.ts
wip: return c token accounts by owner
transfer: spending inutxos +test
cleanup
cleanup address comments
up
=> feat: lamports tests to zero inputs

cli/src/commands/create-mint/index.ts, cli/src/commands/mint-to/index.ts, cli/src/commands/transfer/index.ts, cli/test/commands/create-mint/index.test.ts
Flags updated:
1. create-mint: --mint-keypair flag expects file path to the keypair (optional).
2. mint-to: --mint-authority flag expects file path to the keypair (optional, defaults to $HOME/.config/solana/id.json).
3. transfer: --fee-payer flag expects file path to the keypair (optional, defaults to $HOME/.config/solana/id.json).
=> feat: cli: get keypairs by file paths when using create-mint, mint-to & transfer commands

merkle-tree/concurrent/src/lib.rs, programs/account-compression/src/errors.rs, programs/account-compression/src/instructions/append_leaves.rs, programs/account-compression/src/instructions/initialize_concurrent_merkle_tree.rs, programs/account-compression/src/instructions/insert_into_indexed_array.rs, programs/account-compression/src/instructions/nullify_leaves.rs, programs/account-compression/src/instructions/register_program.rs, programs/account-compression/src/lib.rs, programs/account-compression/src/state/public_state_merkle_tree.rs, programs/account-compression/src/utils/check_registered_or_signer.rs, programs/account-compression/tests/group_authority_tests.rs, programs/account-compression/tests/merkle_tree_tests.rs, programs/compressed-pda/src/append_state.rs, programs/compressed-pda/src/compressed_account.rs, programs/compressed-pda/src/instructions.rs, programs/compressed-pda/src/nullify_state.rs, programs/compressed-pda/src/verify_state.rs, programs/compressed-token/src/process_mint.rs, programs/compressed-token/src/process_transfer.rs, programs/compressed-token/tests/test.rs, test-utils/src/test_env.rs
Changes:
- account compression program:
- enabled group access control
- moved group tests to separate file
- added failing tests for merkle tree append, nullify, insert into indexed array
- linked merkle tree account and indexed array by pubkey and checking these in nullify instruction
=> feat: enable acp group access control

Cargo.lock, Cargo.toml
We are using only upstream 0.4.0 arkworks crates now, there is no need to point to patched 0.3.0 crates.
=> chore: Remove patched arkworks crates

js/stateless.js/src/actions/common.ts, js/stateless.js/src/actions/compress-lamports.ts, js/stateless.js/src/actions/decompress-lamports.ts, js/stateless.js/src/actions/index.ts, js/stateless.js/src/actions/init-sol-omnibus-account.ts, js/stateless.js/src/index.ts, js/stateless.js/src/programs/compressed-pda.ts, js/stateless.js/tests/e2e/compress.test.ts
and initSolOmnibusAccount (wraps initCompressSolPda
- we can adapt naming later if we find a better alternative than both this and initCompressSolPda. changing will be low effort.
- using initCompressSolPda would IMO be easy to confuse with the action of actually creating a pda/compressed pda
- includes the happy path tests. will add tests for payer != initAuthority and payer != compressRecipient in a separate pr such as to unblock the cli now.
=> feat: actions for compressLamports, decompressLamports

cli/package.json, cli/src/commands/compress-sol/index.ts, cli/src/commands/decompress-sol/index.ts, cli/test/commands/compress-sol/index.test.ts, cli/test/commands/decompress-sol/index.test.ts, pnpm-lock.yaml
New CLI commands `compress-sol` and `decompress-sol` have been added:
• `compress-sol --amount <value> --to <value>`: compress SOL to an account.
• `decompress-sol --amount <value> --to <value>`: decompress SOL to an account.
=> feat: add SOL compression and decompression cli commands

js/compressed-token/package.json, js/compressed-token/src/idl/psp_compressed_token.ts, js/compressed-token/src/instructions/transfer.ts, js/compressed-token/src/types.ts, pnpm-lock.yaml, programs/compressed-token/src/lib.rs, programs/compressed-token/src/process_transfer.rs, programs/compressed-token/tests/test.rs
- remove compress input accounts from instruction data
- create new input type which contains only the essential information of input token data and indices for merkle tree and nullifier queue in remaining accounts
- delegate is not enabled yet, also we cannot have any delegated amounts since we don't have an approve instruction.
=> refactor: optimized compressed token transfer instruction data

cli/scripts/photon2bin.sh, cli/src/commands/test-validator/index.ts, cli/src/psp-utils/process.ts, cli/src/utils/initTestEnv.ts
Flags updated:
```
FLAGS
-i, --without_indexer       Runs a test validator without indexer service.
-p, --without_prover        Runs a test validator without prover service.
```
=> refactor: cli test-validator initialization

merkle-tree/hash-set/src/lib.rs
Before this change, we were converting `usize` to `I` and then to `BigUint`. Which is unnecessary, since we can just convert `usize` to `BigUint`.
=> style: Remove unnecessary integer conversion

Cargo.lock, circuit-lib/circuitlib-rs/Cargo.toml, circuit-lib/circuitlib-rs/src/inclusion/merkle_inclusion_proof_inputs.rs, examples/token-escrow/programs/token-escrow/Cargo.toml, merkle-tree/bounded-vec/Cargo.toml, merkle-tree/concurrent/Cargo.toml, merkle-tree/hash-set/Cargo.toml, merkle-tree/hasher/Cargo.toml, merkle-tree/indexed/Cargo.toml, programs/account-compression/Cargo.toml, programs/compressed-pda/Cargo.toml, programs/compressed-token/Cargo.toml, programs/registry/Cargo.toml, programs/user-registry/Cargo.toml, scripts/install.sh, test-utils/Cargo.toml, utils/Cargo.toml
We do it mainly for the new definition of `TransactionSimulationDetails`
in solana-banks-interface 1.18, which contains `inner_instructions`[0].
It will allow us to mock the indexer in Rust tests properly - by fetching
noop program instruction data. This way we could stop returning the
events in instructions and use only the noop program.
[0] https://docs.rs/solana-banks-interface/1.18.11/solana_banks_interface/struct.TransactionSimulationDetails.html
=> chore: Update Solana to 1.18.11

Cargo.lock, Cargo.toml, programs/compressed-pda/Cargo.toml, programs/compressed-pda/src/event.rs, programs/compressed-pda/src/instructions.rs, programs/compressed-pda/src/lib.rs, programs/compressed-pda/tests/test.rs, programs/compressed-token/tests/test.rs, test-utils/src/lib.rs
Before this change, we were returning events in instructions, which is redundant and easily triggers the errors due to return data limit. Here events are only logged in the noop program and mock indexer is retrieving them from inner instructions.
=> test: Read events from inner instructions

merkle-tree/indexed/src/reference.rs, pnpm-lock.yaml, programs/account-compression/src/instructions/append_leaves.rs, programs/compressed-pda/src/verify_state.rs, programs/compressed-pda/tests/test.rs, programs/compressed-token/src/spl_compression.rs
addresses comments from https://github.com/Lightprotocol/light-protocol/pull/630
Changes:
- enable heap neutrality again for signer check
- removed multiple leftover comments
=> chore: remove comments

programs/compressed-pda/src/event.rs, programs/compressed-pda/src/instructions.rs, programs/compressed-pda/src/lib.rs, programs/compressed-token/src/process_transfer.rs
Borsh's `try_to_vec` often allocates more memory than necessary.
=> perf: Avoid `try_to_vec`, define the capacity of buffers manually

programs/account-compression/src/instructions/insert_into_nullifier_queue.rs, programs/compressed-pda/src/nullify_state.rs, programs/compressed-token/tests/test.rs
Changes:
- refactored transfer test to test:
- 1 in 1..11 outputs
- 2 in 1..11 outputs
- 3 in 1..11 outputs
- 4 in 1..11 outputs
- 8 in 1..8 outputs
- removed onchain prints
=> refactor: token transfer test

examples/token-escrow/programs/token-escrow/src/escrow_with_compressed_pda/sdk.rs, examples/token-escrow/programs/token-escrow/src/escrow_with_pda/sdk.rs, js/stateless.js/src/idls/account_compression.ts, js/stateless.js/src/idls/light_compressed_pda.ts, programs/account-compression/src/instructions/append_leaves.rs, programs/account-compression/src/instructions/insert_into_nullifier_queue.rs, programs/account-compression/src/instructions/nullify_leaves.rs, programs/account-compression/src/lib.rs, programs/account-compression/src/sdk.rs, programs/account-compression/src/state/change_log_event.rs, programs/account-compression/src/utils/constants.rs, programs/account-compression/tests/merkle_tree_tests.rs, programs/compressed-pda/src/errors.rs, programs/compressed-pda/src/invoke/append_state.rs, programs/compressed-pda/src/invoke/emit_event.rs, programs/compressed-pda/src/invoke/nullify_state.rs, programs/compressed-pda/src/invoke_cpi/verify_signer.rs, programs/compressed-pda/src/sdk/invoke.rs, programs/compressed-token/src/process_mint.rs, programs/compressed-token/src/process_transfer.rs, programs/compressed-token/tests/test.rs, test-programs/program-owned-account-test/src/sdk.rs
Changes:
- removed NOOP from str calls
- removed HashMap in append_state.rs
- this forced me to refactor append_leaves as well
- switched append state to rust native cpi
- switched nullify state to rust native cpi
- didn't refactor the hashmap on the nullifier queue side here because it didn't seem worth it
- but can get back to that in case that we still have time pre audit
-  hardcoded bumpseed for native cpis
=> perf: cpda program switch to native cpi

Cargo.lock, programs/account-compression/src/processor/initialize_address_merkle_tree.rs, programs/account-compression/src/processor/initialize_address_queue.rs, programs/account-compression/src/processor/initialize_concurrent_merkle_tree.rs, programs/account-compression/src/processor/initialize_nullifier_queue.rs, utils/src/fee.rs, utils/src/lib.rs, xtask/Cargo.toml, xtask/src/fee.rs, xtask/src/main.rs
* Move `compute_rollover_fee` to `light-utils` crate, so it can be imported anywhere without cyclic dependencies.
* Take `height` instead of `number_of_leaves` as an argument. The pattern for number of leaves is always the same (`1 << height`), so doing it inside `compute_rollover_fee` makes sense.
* Add `cargo xtask fee` subcommand instead of unit test. Calculate the rent for different accounts on demand instead of hard coding.
* Avoid hard coding fees and rent in unit tests.
=> refactor: Rollover fee computing and assertions

examples/token-escrow/programs/token-escrow/src/escrow_with_pda/sdk.rs, programs/compressed-pda/src/invoke/append_state.rs, programs/compressed-pda/src/invoke_cpi/processor.rs, programs/compressed-token/src/process_transfer.rs, test-programs/compressed-token-test/Cargo.toml
Issue:
- if not all output Merkle tree indices are provided we didn't append all output compressed accounts to a state Merkle tree
- there is a bug in the compressed token transfer instruction method that doesn't create enough output indices
Changes:
- [append_state.rs](https://github.com/Lightprotocol/light-protocol/pull/688/files#diff-659f5e4f0f52ebc162eccbd75ce52338debd996979398f8db1506692ab6e3fea) iterate over compressed output account instead of output indices to make sure that we insert every output account into a Merkle tree
- fixed the bug in compressed token transfer instruction creation
=> fix: token instruction creation & add onchain check

programs/package.json
Fix for the error:
```
git switch main && git clean -dfx && ./scripts/install.sh && . ./scripts.devenv.sh && ./scripts/build.sh && cd programs && pnpm test-account-compression
[2024-05-08T14:08:56.070303000Z ERROR cargo_build_sbf] Unable to get file metadata for light-protocol/target/sbf-solana-solana/release/account_compression_test.so: No such file or directory (os error 2)
```
=> fix: missing sbf-solana-solana/release/*_test.so

.github/workflows/prover-release.yml, .github/workflows/release.yml
* Run `prover-release.yml` only for `light-prover*` tags, not for all tags. Doing so for all tags results in prover binaries attached to unrelated releases.
* Activate devenv to make sure that Anchor and all other dependencies are there.
=> ci: Fix the release jobs

gnark-prover/main.go
The default addresses for both the prover and metrics servers have been updated from localhost to 0.0.0.0.
=> feat: Update default prover and metrics server addresses

Cargo.lock, merkle-tree/hash-set/Cargo.toml, merkle-tree/hash-set/src/lib.rs, utils/src/lib.rs
Issue:
- multiple indentical values can be inserted into the hashset:
1. insert 2 nullifiers into the hashset with overlapping probing indices
// nullifier_1 has probing indices 1, and 2 -> is inserted in 1
// nullifier_2 hash probing indices 1 and 3 -> is inserted after nullifier_1 in 3
2. mark nullifier_1 with sequence 2401
3. wait until sequence is 2402
4. insert nullfier_2 again this time in position 1
you can reproduce this by setting the 1 in [this line](https://github.com/Lightprotocol/light-protocol/blob/2f71c66d528c8f3df34a46dff5bc9ac6f02b6289/merkle-tree/hash-set/src/lib.rs#L930) to 2399
Changes:
- added find_element_iter
- always loops over the first 20 probe indices of a value
- checks every encountered value for equality throws if yes
- refactored the insert:
- calls …
=> fix: hashset double insert

programs/compressed-pda/src/sdk/address.rs, programs/compressed-pda/src/sdk/compressed_account.rs, programs/compressed-pda/src/sdk/invoke.rs
Issue:
- indices in rust pack functions did not work for multiple input trees
Changes:
- fix the offset and unify index assignment to a single variable
- removed some outdated commented code
=> fix: edge cases in rust sdks

.gitignore, Cargo.lock, programs/account-compression/src/instructions/initialize_state_merkle_tree_and_nullifier_queue.rs, programs/account-compression/src/instructions/insert_into_nullifier_queue.rs, test-programs/account-compression-test/Cargo.toml, test-programs/account-compression-test/tests/merkle_tree_tests.rs, test-programs/compressed-pda-test/tests/test.rs
- add failing test for nullifier queue operations to show that we cannot insert into a full queue.
**Scenario:**
1. try to insert into queue to generate the full error
2. nullify one
3. try to insert again it should still generate the full error
4. advance Merkle tree seq until one before it would work check that it still fails
5. advance Merkle tree seq by one and check that inserting works now
6.try inserting again it should fail with full error
=> test: nullifier queue failing tests full queue

.github/workflows/light-system-programs-tests.yml, examples/token-escrow/programs/token-escrow/Cargo.toml, examples/token-escrow/programs/token-escrow/tests/test.rs, examples/token-escrow/programs/token-escrow/tests/test_compressed_pda.rs, programs/account-compression/src/instructions/initialize_state_merkle_tree_and_nullifier_queue.rs, test-programs/account-compression-test/Cargo.toml, test-programs/account-compression-test/tests/address_merkle_tree_tests.rs, test-programs/account-compression-test/tests/merkle_tree_tests.rs, test-programs/compressed-pda-test/Cargo.toml, test-programs/compressed-pda-test/tests/test.rs, test-programs/compressed-token-test/Cargo.toml, test-programs/compressed-token-test/tests/test.rs, test-programs/program-owned-account-test/Cargo.toml, test-programs/program-owned-account-test/tests/test.rs, test-programs/program-owned-account-test/tests/test_program_owned_trees.rs, test-programs/registry-test/Cargo.toml, test-utils/Cargo.toml, test-utils/src/lib.rs, test-utils/src/spl.rs, test-utils/src/system_program.rs, test-utils/src/test_env.rs, test-utils/src/test_indexer.rs
This is a preparation pr for randomized e2e rust tests.
Changes:
- refactor test indexer:
- works with multiple state and adress Merkle trees
- refactor tests
- to work with new test indexer
- pool test functions in test-utils crate
=> refactor: test indexer

.github/workflows/release-pr-rust.yml, .github/workflows/release.yml
- enforces order of crates for release all, loop individually 
- this should allow us to release all at once 
- adds missing crates to selection
=> chore: all releases in one ci

merkle-tree/indexed/src/array.rs, merkle-tree/indexed/src/errors.rs, merkle-tree/indexed/src/reference.rs, merkle-tree/indexed/tests/tests.rs, test-utils/src/test_forester.rs
Make a clear distinction between methods, which should be used when **inserting** a new element and finding a low element for such insertion operation:
* `find_low_element_for_nonexistent`
* `find_low_element_index_for_nonexistent`
And methods, which should be used for determining a low element for **already existing** element:
* `find_low_element_for_existent`
* `find_low_element_index_for_existent`
=> chore: Provide clear distinction in `find_low_element_*` methods

merkle-tree/bounded-vec/src/lib.rs, merkle-tree/concurrent/src/changelog.rs, merkle-tree/concurrent/src/lib.rs, merkle-tree/concurrent/tests/tests.rs, merkle-tree/indexed/src/copy.rs, merkle-tree/indexed/src/lib.rs, merkle-tree/indexed/src/zero_copy.rs, merkle-tree/reference/src/lib.rs, merkle-tree/reference/tests/tests.rs
Restore the usage of `ConcurrentMerkleTreeError::CannotUpdateLeaf` error. Throwing an error when any changelog entry that modifies the same leaf we try to update is a right thing to do.
In case of indexed Merkle tree, we can ignore this error. We are already patching the leaf using the indexed changelog.
Other changes:
* Fix `test_100_nullify_mt`:
* Each Merkle tree update was pointing to old `changelog_index`. And the crank Merkle tree was not being updated after each operation.
* Implement `Clone` in `BoundedVec`, to make cloning of Merkle proofs possible.
* Add more tests:
* Check whether elements returned in `ConcurrentMerkleTree::changelog_entries`
are as expected.
* Test proving that we need to `skip(1)` during Merkle proof update.
* Test with an update on wrapped-around changelog.
=> fix: Handle conflicting changelogs in concurrent Merkle tree

.github/workflows/release.yml
Set the `package` and `language` variables only if a release commit was found.
Guard all steps after `extract-project` with `if` statements which make sure they're executed only if these variables are set.
=> ci: Make sure we don't try to release when not expected

Cargo.lock, merkle-tree/concurrent/src/event.rs, merkle-tree/concurrent/src/lib.rs, merkle-tree/concurrent/tests/tests.rs, merkle-tree/indexed/src/copy.rs, merkle-tree/indexed/src/lib.rs, merkle-tree/indexed/src/zero_copy.rs, merkle-tree/indexed/tests/tests.rs, programs/account-compression/src/instructions/nullify_leaves.rs, programs/account-compression/src/instructions/update_address_merkle_tree.rs, test-programs/account-compression-test/tests/merkle_tree_tests.rs, test-utils/src/test_forester.rs, xtask/src/type_sizes.rs
Issue:
- previous address event was not emitting enough data
- previous nullify event was emitting unnecessary data
- unfortunately unifying both events into one failed
Changes:
- rename ``ChangelogEvent`` -> ``MerkleTreeEvent``
- refactor ``MerkleTreeEvent::V2`` -> ``NullifierEvent``
- add ``MerkleTreeEvent::V3`` -> ``IndexedMerkleTreeEvent``
=> refactor: events

utils/src/bigint.rs
Before this change, the test was randomly failing. That's because `rng.gen_biguint`, even though it takes number of bits as a limit, sometimes generates smaller numbers, which can fit into smaller byte array than expected.
To make the test reliable, don't use any randomized values. Instead, instantiate `BigUint` values from byte slices.
Also, make sure that both `le` and `be` variants are tested.
=> test: Fix `test_bigint_conversion_invalid_size`

.github/workflows/light-system-programs-tests.yml, .github/workflows/rust.yml
Issue:
- warnings in tests are dangerous and should not exist
Changes:
- add -D warnings rust flag for rust and program ci workflows
- removed unnecessary build in rust ci workflow
=> refactor: ci deny warnings

js/stateless.js/src/actions/create-account.ts, js/stateless.js/src/actions/transfer.ts, js/stateless.js/src/constants.ts, js/stateless.js/src/programs/system.ts, js/stateless.js/src/rpc-interface.ts, js/stateless.js/src/rpc.ts, js/stateless.js/src/test-helpers/test-rpc/test-rpc.ts, js/stateless.js/tests/e2e/compress.test.ts, programs/account-compression/src/instructions/insert_address.rs
* refactors test-rpc
* combined proofs as part of getValidityProof with unified interface
* added test coverage for account creation with compressed lamports (using combined proofs)
* removes an address print on-chain
=> feat: combined proofs and validityProof refactor in rpc-interface

js/compressed-token/src/idl/light_compressed_token.ts, js/stateless.js/src/idls/light_compressed_token.ts, js/stateless.js/src/idls/light_system_program.ts, programs/system/src/invoke/append_state.rs, programs/system/src/invoke/emit_event.rs, programs/system/src/invoke/nullify_state.rs, programs/system/src/invoke/processor.rs, programs/system/src/invoke_cpi/verify_signer.rs, programs/system/src/sdk/event.rs, test-utils/src/assert_compressed_tx.rs, test-utils/src/assert_token_tx.rs
Issue:
- we removed changelog events
- public transaction events contain the input compressed account hashes but no sequence number
Changes:
- add sequence number for every output state Merkle tree to public transaction event
=> feat: public transaction event add seq

cli/src/commands/create-mint/index.ts, cli/src/commands/register-mint/index.ts, cli/test/commands/create-mint/index.test.ts, cli/test/helpers/helpers.ts, examples/token-escrow/README.md, js/compressed-token/src/actions/create-mint.ts, js/compressed-token/src/actions/register-mint.ts, js/compressed-token/src/constants.ts, js/compressed-token/src/idl/light_compressed_token.ts, js/compressed-token/src/program.ts, js/compressed-token/tests/e2e/approve-and-mint-to.test.ts, js/compressed-token/tests/e2e/compress.test.ts, js/compressed-token/tests/e2e/create-mint.test.ts, js/compressed-token/tests/e2e/decompress.test.ts, js/compressed-token/tests/e2e/mint-to.test.ts, js/compressed-token/tests/e2e/register-mint.test.ts, js/compressed-token/tests/e2e/rpc-token-interop.test.ts, js/compressed-token/tests/e2e/transfer.test.ts, js/stateless.js/src/idls/light_compressed_token.ts, js/stateless.js/src/test-helpers/merkle-tree/indexed-array.ts, programs/compressed-token/src/lib.rs, programs/compressed-token/src/process_mint.rs, programs/compressed-token/src/process_transfer.rs, programs/system/src/invoke_cpi/verify_signer.rs, test-utils/src/assert_token_tx.rs, test-utils/src/spl.rs, test-utils/src/test_indexer.rs
compressed-token program:
* `create-mint`: 
* Remove any `authority` signer account. `Create-mint` registers the mint by creating the `tokenPoolPda`
* `tokenPoolPda` is derived from `Mint`, not from `authority`.
* Anyone can create this PDA, which allows any account to compress tokens of said mint.
* This is required so that mints with burned `mintAuthority` can still be compressed.
* `Mint-to`
* `process_mint_to`
* Removed `mintAuthorityPda`, instead...  
* Use static `cpiAuthority` to CPI into the system program. 
* No `mintAuthority` check in our system is required because `mint_spl_to_pool_pda` already does the `mintAuthority` signer check
* CPI into SPL mint-to passes authority (`mintAuthority`), which has to sign the tx
* Added `get_cpi_signer_seeds`() helper because its reused in …
=> chore: rm mintAuthorityPda as proxy signer for mintTo

test-utils/src/test_forester.rs
In the test_forester.rs updated the method call from load_merkle_tree to copy_merkle_tree. This is made to fix the invalid memory reference error that was previously facing in this section.
=> fix: replace load_merkle_tree with copy_merkle_tree in test_forester

cli/package.json, js/compressed-token/package.json, js/stateless.js/package.json, pnpm-lock.yaml, programs/package.json, scripts/build.sh, scripts/test.sh
Simplify build.sh & test.sh  by introducing @lightprotocol/programs dependency for js packages and moving idls scripts to programs build phase
=> chore: simplify build.sh & test.sh

merkle-tree/bounded-vec/src/lib.rs, merkle-tree/concurrent/src/lib.rs, merkle-tree/concurrent/tests/tests.rs, test-programs/account-compression-test/tests/address_merkle_tree_tests.rs
Make sure that:
* `CyclicBoundedVec::iter_from()`
* `ConcurrentMerkleTree::changelog_entries()`
return an empty iterator when the provided `start` value is out of bounds.
=> test: Ensure that `iter_from()` returns an empty iterator when out of bounds

utils/src/fee.rs
Changes:
- add a test to compute and assert that our current rollover fees cover the rentexemption of queue, Merkle tree and cpi context accounts for state and address accounts
=> chore: check rollover fee is high enough

merkle-tree/hash-set/src/lib.rs, merkle-tree/hash-set/src/zero_copy.rs, test-utils/src/e2e_test_env.rs, test-utils/src/test_forester.rs
Issue:
- iterator of hashset was broken
- hash_set.iter().collect returned []
Changes:
- test_forester.rs
- use get_bucket instead of iterator
- hashset
- remove iterator
=> fix: e2e test nullification, remove broken hashset iterator

programs/package.json
Attempting to build and test the light-protocol from a clean state results in an error. 
This pull request fixes the problem by rebuilding the programs with the `cpi-context` feature enabled.
```
[2024-06-03T11:48:46.184015370Z DEBUG solana_runtime::message_processor::stable_log] Program log: Instruction: Transfer
[2024-06-03T11:48:46.184230185Z DEBUG solana_runtime::message_processor::stable_log] Program log: panicked at programs/compressed-token/src/process_transfer.rs:220:9:
not implemented: cpi-context feature is not enabled
[2024-06-03T11:48:46.184241553Z DEBUG solana_runtime::message_processor::stable_log] Program HXVfQ44ATEi9WBKLSCCwM54KokdkzqXci9xCQ7ST9SYN consumed 24514 of 1358937 compute units
[2024-06-03T11:48:46.184259832Z DEBUG solana_runtime::message_processor::stable_log] …
```
=> chore: build system & compressed-token programs with cpi-context feature enabled via programs/package.json

cli/src/utils/constants.ts, js/compressed-token/package.json, js/stateless.js/package.json, js/stateless.js/src/rpc-interface.ts, js/stateless.js/src/rpc.ts, js/stateless.js/src/test-helpers/test-rpc/test-rpc.ts, js/stateless.js/tests/e2e/rpc-interop.test.ts, pnpm-lock.yaml, scripts/install.sh
1) updated to photon 0.21.0. prev. interop tests are now again enabled in CI.
2) added new interop tests  for:
* getValidityProof (inclusion, non-inclusion, combined)
* getMultipleNewAddressProofs 
none of those work with photon yet, therefore these tests are being skipped in CI.
To run them locally for debugging Photon, remove the `.skip` part for the test you want to run.
file: js/stateless.js/tests/e2e/rpc-interop.test.ts
run: `pnpm test:e2e:rpc-interop`
Note than in TS those do not cover foresting events yet (emptying nullifier queue, emptying address queue), but i think fixing these should be a good starting point.
=> chore: rpc-interop with photon 0.21.0

merkle-tree/reference/src/lib.rs, merkle-tree/reference/tests/tests.rs, test-utils/src/indexer/test_indexer.rs
Iterate over hashes and get data directly from self.state_merkle_trees instead of using self.compressed_accounts array to mitigate the out-of-sync forester<=>test_indexer state issue.
=> refactor: test_indexer's `get_multiple_compressed_account_proofs` method

js/compressed-token/tests/e2e/rpc-token-interop.test.ts, js/stateless.js/src/actions/transfer.ts, js/stateless.js/src/rpc.ts, js/stateless.js/src/test-helpers/test-rpc/test-rpc.ts, js/stateless.js/tests/e2e/rpc-interop.test.ts
* don't compare zkps by value, instead use them to execute a transaction.
=> fix: asserts in rpc-interop tests

.cargo/config.toml
The path to lld linker for the aarch64-apple-darwin target in rustflags has been simplified. 
The previous long path has been replaced with the shorter "-fuse-ld=lld".
=> chore: update rustflags for aarch64-apple-darwin target

merkle-tree/hash-set/src/lib.rs, merkle-tree/hash-set/src/zero_copy.rs, programs/account-compression/src/state/queue.rs
Some methods were not covered. This change achieves full coverage.
=> test: Add more unit tests for `light-hash-set`

scripts/install.sh
This change helps users avoid compilation errors related to conflicting dependency versions.
=> chore: avoid compilation errors on linux-arm64

merkle-tree/bounded-vec/src/lib.rs
Some methods were not covered. This change achieves full coverage.
=> test: Add more unit tests for `BoundedVec` and `CyclicBoundedVec`

scripts/coverage.sh
It's named `coverage.sh` and uses `cargo-llvm-cov`[0].
[0] https://github.com/taiki-e/cargo-llvm-cov
=> build: Add script for reporting coverage methods

utils/src/lib.rs
=> test: Add more tests for `light_utils` main module

forester/tests/e2e_test.rs, forester/tests/empty_address_tree_test.rs, programs/account-compression/src/processor/initialize_address_merkle_tree.rs, test-programs/account-compression-test/tests/address_merkle_tree_tests.rs, test-programs/e2e-test/tests/test.rs, test-programs/system-cpi-test/tests/test_program_owned_trees.rs, test-utils/src/assert_queue.rs, test-utils/src/e2e_test_env.rs, test-utils/src/indexer/test_indexer.rs, test-utils/src/test_env.rs, test-utils/src/transaction_params.rs
depends on: https://github.com/Lightprotocol/light-protocol/pull/872
Changes:
- add option to init trees with random changelog, root history array and rollover threshold parameters
=> chore: add flexible changelog root history arrays e2e test

.github/workflows/pr.yml
The "deps" and "deps-dev" have been added to the .github/workflows/pr.yml file.
=> chore: add "deps" and "deps-dev" to pr.yml workflow

programs/account-compression/src/instructions/initialize_address_merkle_tree_and_queue.rs, programs/account-compression/src/instructions/initialize_state_merkle_tree_and_nullifier_queue.rs, test-programs/account-compression-test/tests/address_merkle_tree_tests.rs, test-programs/account-compression-test/tests/merkle_tree_tests.rs, test-programs/system-cpi-test/tests/test_program_owned_trees.rs, test-utils/src/address_tree_rollover.rs, test-utils/src/e2e_test_env.rs, test-utils/src/indexer/test_indexer.rs, test-utils/src/state_tree_rollover.rs, test-utils/src/test_env.rs, test-utils/src/test_forester.rs, utils/src/prime.rs
Initialize queues with non-default sizes and use them in all functional tests to make sure that zero-copy serialization works.
=> test: Use on-chain queues with different sizes

programs/account-compression/src/errors.rs, programs/account-compression/src/instructions/initialize_address_merkle_tree_and_queue.rs, programs/account-compression/src/instructions/initialize_state_merkle_tree_and_nullifier_queue.rs, test-programs/account-compression-test/tests/address_merkle_tree_tests.rs, test-programs/account-compression-test/tests/merkle_tree_tests.rs
Return errors for:
- Height different than 26.
- Canopy depth different than 10.
- Sequence threshold lower than roots + safety margin.
=> chore: Return errors for unsupported configurations

test-programs/account-compression-test/tests/address_merkle_tree_tests.rs
Before this change, we were not passing the `queue_config` to the instruction.
=> test: Test different queue configs (for real)

js/compressed-token/src/idl/light_compressed_token.ts, js/stateless.js/src/idls/account_compression.ts, js/stateless.js/src/idls/light_compressed_token.ts, js/stateless.js/src/idls/light_system_program.ts, programs/account-compression/src/errors.rs, programs/account-compression/src/instructions/insert_into_queues.rs, programs/account-compression/src/instructions/nullify_leaves.rs, programs/account-compression/src/instructions/register_program.rs, programs/account-compression/src/instructions/update_address_merkle_tree.rs, programs/account-compression/src/lib.rs, programs/system/src/errors.rs, programs/system/src/invoke/append_state.rs, programs/system/src/invoke/instruction.rs, programs/system/src/invoke/nullify_state.rs, programs/system/src/invoke/processor.rs, programs/system/src/invoke/sol_compression.rs, programs/system/src/invoke/verify_signer.rs, programs/system/src/invoke/verify_state_proof.rs, programs/system/src/invoke_cpi/process_cpi_context.rs, programs/system/src/invoke_cpi/verify_signer.rs, programs/system/src/lib.rs, programs/system/src/sdk/compressed_account.rs, test-programs/account-compression-test/tests/address_merkle_tree_tests.rs, test-programs/account-compression-test/tests/merkle_tree_tests.rs, test-utils/src/test_forester.rs
Changes:
- removed unused errors
- nullify leaves rename `indices` -> `leaf_indices`
- register program replace address constraint with constraint with same functionality because anchor 0.30. idl generation doesn't like address constraints
- update_address_merkle_tree - add comments, move address indexed element down, replace sequence_number with `merkle_tree.sequence_number` after it has been incremented
- append_state refactor index_merkle_tree_account to start at zero and be incremented with every iteration
- invoke/processor.rs - rename `roots` to `input_compressed_account_roots`
- invoke/processor.rs - remove deduplication of sequence numbers, its not needed anymore since we enforce ordered output Merkle trees
- rename `fetch_roots` -> `fetch_input_compressed_account_roots`
- …
=> chore: review-cleanup

forester/src/main.rs, forester/src/nullifier/address/pipeline.rs, forester/src/nullifier/address/processor.rs, forester/src/nullifier/pipeline_context.rs, forester/src/nullifier/state/pipeline.rs, forester/src/nullifier/state/processor.rs, forester/src/operations.rs, forester/tests/empty_address_tree_test.rs, test-utils/src/indexer/mod.rs, test-utils/src/indexer/test_indexer.rs
1. Improved retry logic on address tree foresting
2. Added more logs.
3. Introduced another magic number, it's needed for zktestnet forester until we upgrade to new release: `let indexer_index_changelog = (proof.root_seq - 1) % ADDRESS_MERKLE_TREE_INDEXED_CHANGELOG;`
=> fix: improved retry logic on address tree foresting

merkle-tree/concurrent/src/lib.rs, merkle-tree/concurrent/tests/tests.rs
`fillup_index` used to be our limit of hashes computed for each non-terminal Merkle path in a batched update. However, it didn't work reliably.
`fillup_index` limited to `next_index().trailing_ones()` was resulting in `filled_subtrees` not being updated in case when `fillup_index` was 0.
Incrementing it by 1, which we used to do, was a workaround which worked for the most cases in a sense of producing correct roots, but the non-terminal Merkle paths were incorrect - they contained one node too many.
Here we are introducing a different approach where we always iterate in `0..self.height` range, but we break the loop as soon as we encounter a node on the left. Before breaking the loop, we update `filled_subtrees`. Therefore, both `filled_subtrees` and all Merkle paths are correct.
=> fix: Correct the `fillup_index`

test-utils/src/e2e_test_env.rs, utils/src/prime.rs, utils/src/rand.rs, xtask/src/hash_set.rs
* Before this change, calling `find_next_prime` with a candidate which satisfies `6k + 1` pattern did not work. This pattern was only later in the loop, but not for the original `n` argument.
* Use `u32` as a type for `n`. It's safe to convert `u32` into `f64` without precission loss.
=> fix: Handle `6k + 1` candidates properly

merkle-tree/concurrent/src/hash.rs, merkle-tree/concurrent/src/lib.rs
The latter is more clear and widely used in the rest of the code.
=> style: Rename `sibling_index` to `level`

merkle-tree/concurrent/src/lib.rs
Paths in changelog contain also roots.
=> fix: Use the correct size (`self.height + 1`) for Merkle `path`

merkle-tree/indexed/src/errors.rs, merkle-tree/indexed/src/lib.rs, merkle-tree/indexed/tests/tests.rs, programs/account-compression/src/instructions/update_address_merkle_tree.rs
* Instead of consuming `new_element` as `IndexedElement`, take only a `BigUint` value, then instantiate an `IndexedElement` using the current `index` from Merkle tree (as `index`) and `next_index` from `low_element`.
* That manually instantiated `IndexedElement` is still a subject to change by `patch_elements_and_proof` to preserve concurrency.
* Remove the `NewElementNextIndexMismatch`, as we don't allow users to specify `next_index`.
=> fix: Pass only the value of new element to `update`

merkle-tree/hasher/src/errors.rs
Before this change, multiple variants were using `7002`.
=> chore: Assign distinct error codes in `HasherError` variants

merkle-tree/bounded-vec/src/lib.rs
This was not resulting in any reproducable issue, because `inc_last_index` and `inc_first_index` are always called together. However, this could lead to issues in future code changes.
=> fix: Increment `first_index` correctly in `inc_first_index`

merkle-tree/concurrent/src/lib.rs, merkle-tree/concurrent/tests/tests.rs, merkle-tree/reference/src/lib.rs
Before this change, we were updating canopy only after appends. Now we do it also for updates.
Add unit tests which assert the whole canopy.
=> fix: Update canopy after Merkle tree updates

js/stateless.js/src/idls/account_compression.ts, js/stateless.js/src/idls/light_registry.ts, js/stateless.js/src/idls/light_system_program.ts, programs/account-compression/src/instructions/initialize_address_merkle_tree_and_queue.rs, programs/account-compression/src/instructions/initialize_state_merkle_tree_and_nullifier_queue.rs, programs/account-compression/src/lib.rs, programs/account-compression/src/sdk.rs, programs/registry/src/lib.rs, programs/registry/src/sdk.rs, programs/system/src/errors.rs, programs/system/src/invoke/instruction.rs, programs/system/src/invoke/processor.rs, programs/system/src/invoke_cpi/verify_signer.rs, test-programs/account-compression-test/tests/address_merkle_tree_tests.rs, test-programs/account-compression-test/tests/merkle_tree_tests.rs, test-programs/registry-test/tests/tests.rs, test-programs/system-cpi-test/src/lib.rs, test-programs/system-cpi-test/src/sdk.rs, test-programs/system-cpi-test/tests/test_program_owned_trees.rs, test-utils/src/e2e_test_env.rs, test-utils/src/indexer/test_indexer.rs, test-utils/src/test_env.rs
Changes:
- merkle trees should be owned by the pubkey or group which is creating them
- add signer check to enforce this
=> chore: guard init merkle trees

merkle-tree/indexed/src/lib.rs
Changes:
- remove unused and non functional indexed Merkle tree typ definitions
=> chore: remove unused indexed Merkle tree type definitions

merkle-tree/hash-set/src/lib.rs, merkle-tree/hash-set/src/zero_copy.rs, merkle-tree/indexed/tests/tests.rs, programs/account-compression/src/instructions/nullify_leaves.rs, programs/account-compression/src/instructions/update_address_merkle_tree.rs, xtask/src/hash_set.rs
* Using a value was a bad choice, because it caused `mark_with_sequence_number` to search for the element. In all cases, where we use that method, we usually have the index available.
* Return the index in `HashSet::insert`, for easier testing.
=> perf: Use index as an argument in `HashSet::mark_with_sequence_number`

programs/system/src/invoke/verify_state_proof.rs
Changes:
- remove error of unordered input accounts
- add check whether a hashed Merkle tree pubkey already has been hashed
=> fix: allow unordered input compressed accounts

merkle-tree/concurrent/src/copy.rs, merkle-tree/concurrent/src/errors.rs, merkle-tree/concurrent/src/lib.rs, merkle-tree/concurrent/src/zero_copy.rs, test-programs/account-compression-test/tests/address_merkle_tree_tests.rs, test-programs/account-compression-test/tests/merkle_tree_tests.rs, test-utils/src/assert_address_merkle_tree.rs, test-utils/src/test_env.rs
* Validate changelog and roots size not only in `new()` method, but also in `init()` and all wrapper types (zero-copy and copy).
* Add SBF tests which initialize trees with zero capacities and expect an error.
* Add SBF tests with changelog and root capacity 1. They are expected to succeed.
=> fix: Handle invalid (zero) capacity of changelog and roots reliably

circuit-lib/light-prover-client/src/init_merkle_tree.rs, circuit-lib/light-prover-client/src/non_inclusion/merkle_non_inclusion_proof_inputs.rs, examples/token-escrow/programs/token-escrow/tests/test.rs, examples/token-escrow/programs/token-escrow/tests/test_compressed_pda.rs, forester/tests/e2e_test.rs, forester/tests/empty_address_tree_test.rs, forester/tests/interop_address_test.rs, forester/tests/interop_nullify_test.rs, forester/tests/test_utils.rs, merkle-tree/indexed/src/array.rs, merkle-tree/indexed/src/lib.rs, merkle-tree/indexed/src/reference.rs, merkle-tree/indexed/tests/tests.rs, test-programs/account-compression-test/tests/address_merkle_tree_tests.rs, test-programs/account-compression-test/tests/group_authority_tests.rs, test-programs/account-compression-test/tests/merkle_tree_tests.rs, test-programs/compressed-token-test/tests/test.rs, test-programs/e2e-test/tests/test.rs, test-programs/system-cpi-test/tests/test.rs, test-programs/system-cpi-test/tests/test_program_owned_trees.rs, test-programs/system-test/tests/test.rs, test-utils/src/assert_compressed_tx.rs, test-utils/src/assert_token_tx.rs, test-utils/src/e2e_test_env.rs, test-utils/src/indexer/test_indexer.rs, test-utils/src/spl.rs, test-utils/src/system_program.rs, test-utils/src/test_forester.rs
Changes:
- replace constant sized array and remove const generic from IndexedArray struct
- this will enable us to use bigger indexed arrays in tests
=> chore: switch indexed array to vec

merkle-tree/bounded-vec/src/lib.rs, utils/src/offset/copy.rs
Ensure that the metadata are being restored correctly and that the new copy points to the correct `first_index`, `last_index`.
=> test: Add a simple test case for `read_cyclic_bounded_vec_at`

programs/account-compression/src/state/change_log_event.rs
Before this change, non-executable programs could pass the noop program check.
=> fix: noop program account check

js/stateless.js/src/idls/account_compression.ts, pnpm-lock.yaml, programs/account-compression/src/errors.rs, programs/account-compression/src/instructions/initialize_address_merkle_tree_and_queue.rs, programs/account-compression/src/instructions/initialize_state_merkle_tree_and_nullifier_queue.rs, programs/account-compression/src/instructions/rollover_address_merkle_tree_and_queue.rs, programs/account-compression/src/instructions/rollover_state_merkle_tree_and_queue.rs, programs/account-compression/src/utils/check_account.rs, test-programs/account-compression-test/tests/address_merkle_tree_tests.rs, test-programs/account-compression-test/tests/merkle_tree_tests.rs
Changes:
- introduce expected size check in `process_initialize_address_merkle_tree_and_queue` `process_initialize_state_merkle_tree_and_nullifier_queue`
- in rollover instructions unify `assert_size_equal` with `check_account_balance_is_rent_exempt`
=> fix: assert account sizes at init and unify rollover account size check

Cargo.lock, programs/compressed-token/src/lib.rs, programs/compressed-token/src/process_mint.rs, test-programs/compressed-token-test/Cargo.toml, test-programs/compressed-token-test/tests/test.rs
Test cases:
1. Try to mint token from `mint_1` and sign the transaction with `mint_2` authority.
2. Try to mint token from `mint_2` and sign the transaction with `mint_1` authority.
3. Try to mint token from `mint_1` while using `mint_2` pool.
4. Try to mint token from `mint_2` while using `mint_1` pool.
5. Invalid CPI authority.
6. Invalid registered program.
7. Invalid noop program.
8. Invalid account compression authority.
9. Invalid Merkle tree.
10. Mint more than `u64::MAX` tokens.
11. Multiple mints which overflow the token supply over `u64::MAX`.
Related fixes:
- Add `MintTooLarge` error when the sum of mint amounts exceeds `u64::MAX`.
=> test: Failing tests for `mint_to` instruction

test-programs/compressed-token-test/tests/test.rs, test-utils/src/assert_token_tx.rs
Successful tests:
- Delegating `u64::MAX`.
Failing tests:
1. Invalid delegated compressed account Merkle tree.
2. Invalid change compressed account Merkle tree.
3. Invalid proof.
4. Invalid mint.
=> test: More tests for `approve` method of token program

test-programs/compressed-token-test/tests/test.rs
Successful tests:
- Revoke `u64::MAX`.
Failing tests:
1. Invalid root indices.
2. Invalid Merkle tree.
3. Invalid mint.
=> test: More tests for `revoke` method of token program

js/compressed-token/src/idl/light_compressed_token.ts, js/stateless.js/src/idls/light_compressed_token.ts, merkle-tree/hash-set/src/lib.rs, test-programs/account-compression-test/tests/merkle_tree_tests.rs
Issue:
- the current hash-set seems to perform poorly in practice because it iterates only over a small part of the hash-set
Changes:
- increase step size relative to capacity
Note:
- some tests depend on linear filling which does not work anymore because of the increased step size this is expected
- adapted most tests, removed two which were just asserting linear filling
=> fix: add wide hash set steps

programs/compressed-token/src/instructions/freeze.rs, programs/compressed-token/src/lib.rs, test-programs/compressed-token-test/tests/test.rs
- Test freeze and thaw with zero values.
- Failing tests for `freeze`
1. Invalid authority.
2. Invalid Merkle tree.
3. Invalid proof.
- Failing tests for `thaw`
1. Invalid authority.
2. Invalid Merkle tree.
3. Invalid proof.
=> test: Add more test cases for `freeze` instruction in token program

js/compressed-token/src/idl/light_compressed_token.ts, js/compressed-token/tests/e2e/mint-to.test.ts, js/stateless.js/src/idls/light_compressed_token.ts, programs/compressed-token/src/burn.rs, programs/compressed-token/src/freeze.rs, programs/compressed-token/src/instructions/burn.rs, programs/compressed-token/src/instructions/mod.rs, programs/compressed-token/src/lib.rs, programs/system/src/invoke_cpi/verify_signer.rs, test-programs/compressed-token-test/tests/test.rs, test-utils/src/spl.rs
Similarly to the `mint` instruction, where we are minting SPL tokens, burn SPL tokens when calling `burn` instruction.
=> feat: Burn SPL tokens from the pool when burning compressed tokens

merkle-tree/hash-set/src/lib.rs
The Send trait has been unsafely implemented for the HashSet and HashSetCell, making these types able to be sent between threads safely when used properly. 
This allows for potential multi-threading and concurrent usage of these data types.
=> feat: add Send trait for HashSet and HashSetCell

.gitignore, CODEOWNERS, js/compressed-token/src/idl/light_compressed_token.ts, js/stateless.js/src/idls/light_compressed_token.ts, programs/compressed-token/src/delegation.rs, programs/compressed-token/src/freeze.rs, programs/compressed-token/src/instructions/freeze.rs, programs/compressed-token/src/instructions/generic.rs, programs/compressed-token/src/instructions/transfer.rs, programs/compressed-token/src/process_mint.rs, test-programs/compressed-token-test/tests/test.rs
Changes:
- updated instruction comments
- added tests with 8 inputs for `approve` and `revoke`
- replaced remaining `unwrap_err`s
- added failing tests:
- Invalid delegate amount (too high)
- freeze frozen compressed account
- thaw non frozen compressed account
-
=> chore: compressed token tests & cleanup

programs/compressed-token/src/burn.rs, programs/compressed-token/src/delegation.rs, programs/compressed-token/src/freeze.rs, programs/compressed-token/src/lib.rs, programs/compressed-token/src/process_mint.rs, programs/compressed-token/src/process_transfer.rs
changes:
- add and update comments to all instructions in `lib.rs`
- remove duplicate code of manual lamports sum computations in multiple instructions
- adapt manual borsh unit test to explicitly cover case of `lamports=0` in addition to random amounts
- replace push additional lamports change compressed account with `resize` to avoid unnecessary heap memory allocations
=> chore: update and add instruction comments,minor refactors

.github/workflows/js.yml, cli/src/utils/constants.ts, js/compressed-token/package.json, js/compressed-token/src/idl/light_compressed_token.ts, js/compressed-token/tests/e2e/rpc-token-interop.test.ts, js/stateless.js/src/idls/light_compressed_token.ts, js/stateless.js/src/rpc.ts, js/stateless.js/src/test-helpers/test-rpc/get-compressed-token-accounts.ts, js/stateless.js/src/test-helpers/test-rpc/test-rpc.ts, js/stateless.js/src/utils/send-and-confirm.ts, scripts/install.sh
- also bumps to newest photon 0.36.0
- enables token-interop tests
- cli ci
=> fix: wait for photon slot to match rpc slot in confirmTx

programs/compressed-token/src/instructions/transfer.rs, programs/compressed-token/src/lib.rs, programs/compressed-token/src/process_mint.rs, test-programs/compressed-token-test/tests/test.rs
Issues:
- unchecked token pool accounts allowed tokens to move to non-pool accounts during compression
Changes:
- check pool account seeds
=> fix: unchecked token pool account

Cargo.lock, Cargo.toml, circuit-lib/light-prover-client/Cargo.toml, circuit-lib/verifier/Cargo.toml, examples/token-escrow/programs/token-escrow/Cargo.toml, merkle-tree/concurrent/Cargo.toml, programs/registry/Cargo.toml, sdk/Cargo.toml, test-programs/account-compression-test/Cargo.toml, test-programs/compressed-token-test/Cargo.toml, test-programs/e2e-test/Cargo.toml, test-programs/registry-test/Cargo.toml, test-programs/system-cpi-test/Cargo.toml, test-programs/system-test/Cargo.toml, test-utils/Cargo.toml
Replaced individual `tokio` versions with `tokio` specified at the workspace level for consistency across the project.
=> chore: Update `tokio` to workspace-wide specification

hasher.rs/package.json, js/compressed-token/src/idl/light_compressed_token.ts, js/stateless.js/src/idls/account_compression.ts, js/stateless.js/src/idls/light_compressed_token.ts, js/stateless.js/src/idls/light_registry.ts, js/stateless.js/src/idls/light_system_program.ts, scripts/install.sh
* Removed Playwright installation from `install.sh` and updated the `test` script to omit browser tests on hasher.rs. 
* Additionally, bumped the version for multiple IDLs from `0.4.1` to `0.5.0`.
=> chore: remove Playwright install

programs/system/src/errors.rs, programs/system/src/invoke/append_state.rs, test-programs/system-test/tests/test.rs
Issue:
- by passing the same Merkle tree multiple times an attacker is able to create the same leaf hash twice
Changes:
- add uniqueness check for output Merkle trees and failing test
=> fix: add output merkle tree uniqueness check

programs/system/src/errors.rs, programs/system/src/invoke/verify_signer.rs, programs/system/src/invoke_cpi/verify_signer.rs, test-programs/system-cpi-test/src/create_pda.rs, test-programs/system-cpi-test/tests/test.rs, test-programs/system-test/tests/test.rs
Issue:
- program owned accounts can be spend by the program keypair with the `invoke` system program instruction
Solution:
- add check to reject accounts with data as input accounts in `invoke`
- add check to not allow program owned account creation without data
=> fix: spend program owned account with program keypair

programs/compressed-token/src/instructions/transfer.rs, programs/compressed-token/src/lib.rs, programs/compressed-token/src/spl_compression.rs, test-programs/compressed-token-test/tests/test.rs
Issue:
- prior token pool check in transfer instruction was insufficient
Changes:
- create a check token pool derivation function which checks derivation in the compress and decompress function instead of the instruction struct
- added failing test for invalid `token_pool_pda` for compressing tokens, adapted error for failing test with decompression
=> fix: (de)compression transfer ix token pool check

Cargo.lock, programs/compressed-token/src/delegation.rs
Issue:
- compressed token program unit tests do not cover compressed token input accounts with SOL balance
Changes:
- add unit test with SOL balance
=> fix: compressed token program revoke test coverage with sol

programs/compressed-token/src/process_transfer.rs, test-programs/compressed-token-test/tests/test.rs, test-utils/src/assert_token_tx.rs, test-utils/src/e2e_test_env.rs, test-utils/src/spl.rs
Issue:
- consider an escrow program with an compressed escrow token account owned by a pda
- when compressing into this escrow account we have token accounts of two different owners which both need to sign (pda, depositing user)
- The straightforward way is to just transfer the deposit amount to the pda. However, this way every deposit creates an additional escrow account -> the escrowed tokens are fragmented and need to be merged.
- We could merge escrow accounts in the deposit transaction in a second cpi. The implementation is difficult since we need to dynamically get the leaf index of the newly inserted compressed account onchain, then spend the newly created compressed account and verify two zkps in this process. This would only work if there is no activity on the Merkle tree …
=> fix: mix delegated and owned compressed token accounts 

macros/light/src/traits.rs
Before this change, using `#[derive(LightTraits)]` macro required adding necessary imports manually, e.g.
```rust
use light_sdk::traits::{InvokeAccounts, SignerAccounts};
```
Which might've been annoying for developers.
This change uses full paths for all foreign types used inside macros, so no additional imports are needed.
=> fix(macros): Provide full import paths in `LightTraits`

Cargo.lock, macros/light/Cargo.toml, macros/light/src/discriminator.rs, macros/light/src/lib.rs, merkle-tree/hasher/src/lib.rs
This macro generates discriminator for the annotated struct by using its name, hashing it with SHA256 and taking the first 8 bytes.
=> feat: Add `LightDiscriminator` derive macro

Cargo.lock, Cargo.toml, pnpm-lock.yaml
Motivation:
I use the pubsub client from the solana-rpc crate in forester. I switched to 1.18.17 because our 1.18.11 agave branch doesn't work well with this crate.
```
Compiling solana-rpc v1.18.11 (https://github.com/lightprotocol/agave?branch=v1.18.11-enforce-cpi-tracking#a24d3c07)
error[E0308]: mismatched types
--> /Users/tsv/.cargo/git/checkouts/agave-f8c52564d46c9282/a24d3c0/rpc/src/rpc.rs:3677:29
|
3677 | ...                   inner_instructions,
|                       ^^^^^^^^^^^^^^^^^^ expected `Option<Vec<UiInnerInstructions>>`, found `Option<Vec<Vec<InnerInstruction>>>`
|
= note: expected enum `std::option::Option<Vec<UiInnerInstructions>>`
found enum `std::option::Option<Vec<Vec<solana_sdk::inner_instruction::InnerInstruction>>>`
```
=> chore: switch to agave 1.18.17

merkle-tree/concurrent/src/lib.rs, merkle-tree/hash-set/src/lib.rs, merkle-tree/indexed/src/array.rs, merkle-tree/indexed/src/lib.rs
1. HashSet::find_element_index function, the probe index iteration can be limited to 0..20 similar to insertion, avoiding iteration up to capacity. Use a constant instead of the hardcoded value 20.
2. In HashSet::find_element_iter function, it would be better to iterate from start_iter to (`start_iter + num_iterations`) as per the parameter name.
3. In IndexedMerkleTree::add_highest_element function, simplify indexed_array.append(&init_value) with indexed_array.init().
4. In IndexedArray::hash_element, simplify hashing by using element.hash(next_element.value).
5. In ConcurrentMerkleTree::append_batch, use self.next_index instead of first_leaf_index + leaf_i.
=> fix: impl suggestions

examples/token-escrow/programs/token-escrow/src/escrow_with_compressed_pda/withdrawal.rs, js/compressed-token/src/idl/light_compressed_token.ts, js/stateless.js/src/idls/light_compressed_token.ts, js/stateless.js/src/idls/light_system_program.ts, js/stateless.js/src/instruction/pack-compressed-accounts.ts, js/stateless.js/src/state/compressed-account.ts, js/stateless.js/src/state/types.ts, pnpm-lock.yaml, programs/compressed-token/src/freeze.rs, programs/compressed-token/src/process_transfer.rs, programs/system/src/invoke/sum_check.rs, programs/system/src/invoke_cpi/process_cpi_context.rs, programs/system/src/sdk/compressed_account.rs, programs/system/src/sdk/invoke.rs, test-programs/system-cpi-test/tests/test.rs
Changes:
- add placeholder marker to mark input compressed accounts as readonly
- readonly needs to be false else panic with `unimplemented`
=> chore: add read only placeholder

programs/account-compression/src/errors.rs, programs/account-compression/src/instructions/deregister_program.rs, test-programs/account-compression-test/tests/group_authority_tests.rs
Issue:
- anyone can deregister arbitrary programs
Changes:
- add constraint which checks that  `registered_program_pda` is registered with provided `group_authority_pda`
=> fix: deregister program

examples/token-escrow/programs/token-escrow/src/escrow_with_compressed_pda/escrow.rs, examples/token-escrow/programs/token-escrow/src/escrow_with_pda/escrow.rs, macros/light/src/accounts.rs, macros/light/src/traits.rs, programs/compressed-token/src/instructions/burn.rs, programs/compressed-token/src/instructions/freeze.rs, programs/compressed-token/src/instructions/generic.rs, programs/compressed-token/src/instructions/transfer.rs, programs/system/src/invoke/instruction.rs, programs/system/src/invoke_cpi/instruction.rs, programs/system/src/sdk/accounts.rs, sdk/src/traits.rs
Before this change, using `#[light_accounts]` macro required adding necessary imports manually, e.g.
```rust
use account_compression::program::AccountCompression;
use light_system_program::program::LightSystemProgram;
```
Which might've been annoying for developers.
This change uses full paths for all foregin types used inside macros, so no additional imports are needed.
=> fix(macros): Provide full import paths in `light_accounts` macro

cli/src/commands/balance/index.ts, js/compressed-token/package.json, js/compressed-token/src/actions/decompress.ts, js/compressed-token/src/actions/transfer.ts, js/compressed-token/src/idl/light_compressed_token.ts, js/compressed-token/tests/e2e/approve-and-mint-to.test.ts, js/compressed-token/tests/e2e/compress.test.ts, js/compressed-token/tests/e2e/decompress.test.ts, js/compressed-token/tests/e2e/mint-to.test.ts, js/compressed-token/tests/e2e/rpc-token-interop.test.ts, js/compressed-token/tests/e2e/transfer.test.ts, js/stateless.js/package.json, js/stateless.js/src/actions/create-account.ts, js/stateless.js/src/actions/decompress.ts, js/stateless.js/src/actions/transfer.ts, js/stateless.js/src/idls/light_compressed_token.ts, js/stateless.js/src/rpc-interface.ts, js/stateless.js/src/rpc.ts, js/stateless.js/src/test-helpers/test-rpc/get-compressed-token-accounts.ts, js/stateless.js/src/test-helpers/test-rpc/test-rpc.ts, js/stateless.js/tests/e2e/compress.test.ts, js/stateless.js/tests/e2e/rpc-interop.test.ts, js/stateless.js/tests/e2e/test-rpc.test.ts, js/stateless.js/tests/e2e/testnet.test.ts, js/stateless.js/tests/e2e/transfer.test.ts, pnpm-lock.yaml
* bump versions to latest NPM releases
* changes the JS RPC return type for endpoints with cursors. Wraps inside WithCursor<{items, cursor}>, so values need to be accessed like e.g. compressedAccounts.items[0]
=> chore: RPC patch

forester/src/epoch_manager.rs, forester/src/lib.rs, forester/src/pubsub_client.rs, forester/src/queue_helpers.rs, forester/src/utils.rs, forester/tests/e2e_test.rs
* Introduced `setup_pubsub_client` for setting up a PubSub client and fetching queue item data. 
* Extracted queue-related logic into a new `queue_helpers` module. 
* Refactored slot waiting logic into utility functions.
* Removed most unwraps in epoch_manager.
=> refactor: forester: unwraps & code structure

forester/src/epoch_manager.rs, forester/src/errors.rs
Introduced a new error variant `NotEligible` in `ForesterError`. 
Updated the eligibility check to return this error and handle it appropriately during the transaction processing loop.
=> feat: forester: do not retry on not eligible slots

Cargo.lock, macros/light/Cargo.toml, macros/light/src/hasher.rs, macros/light/src/lib.rs, macros/light/tests/hasher.rs, merkle-tree/hasher/Cargo.toml, merkle-tree/hasher/src/bytes.rs, merkle-tree/hasher/src/lib.rs
- `AsByteVec`, providing `as_byte_vec()` method, guarantees consistent way of serializing types to 2D byte vectors before hashing. We provide default implementations for primitives. More complex types need to implement `IntoBytes` themselves.
- By using 2D vectors, we make it possible to represent structs with multiple fields. This way, we can handle struct fields (nested structs) the same way as primitive fields and deal with all types by using one trait.
- The reason behing using vectors instead of slices is that in some cases, we cannot just cast the type without defining custom bytes. Vectors, although they might introduce copies, make sure we always own the bytes we are creating.
- `#[derive(LightHasher)]` implements `AsByteVec` and `DataHasher` traits. The `DataHasher` …
=> feat: `#[derive(LightHasher)]` macro and `AsByteVec` trait

.github/workflows/light-examples-tests.yml, examples/name-service/programs/name-service/src/lib.rs, examples/name-service/programs/name-service/tests/test.rs, sdk/src/merkle_context.rs
- Remove unused import (`errors::HasherError`).
- Allow `clippy::too_many_arguments`.
- Remove `RemainingAccounts::new()` - we can just `#[derive(Default)]` and instantiate with `RemainingAccounts::default()`.
=> fix: Rust compilation and clippy errors

cli/package.json, cli/src/utils/constants.ts, js/stateless.js/src/rpc-interface.ts, js/stateless.js/src/rpc.ts, js/stateless.js/src/test-helpers/test-rpc/test-rpc.ts, js/stateless.js/tests/e2e/rpc-interop.test.ts, pnpm-lock.yaml, scripts/install.sh
upd:
- 0.40.0
- bump to latest ts versions accordingly
- support filter config again in rpc endpoints
=> chore: add memcp filter option to rpc, bump to photon 0.39.0

examples/name-service/programs/name-service/src/lib.rs, macros/light/src/account.rs, macros/light/src/lib.rs
That macro implements all traits necessary for compressed accounts, which inclides:
- `AnchorDeserialize`
- `AnchorSerialize`
- `LightDiscriminator`
- `LightHasher`
=> feat: Add `#[light_account]` macro

README.md, scripts/install.sh
We should export RUSTUP_HOME & CARGO_HOME env vars before installation, otherwise cargo & rustup will be installed to the default path.
=> chore: update install.sh

macros/aligned-sized/src/expand.rs, macros/aligned-sized/tests/test.rs
Before this change, `#[aligned_sized]` macro was still including the size of the original type even on fields using the `size` attribute.
That was an incorrect behavior. The intention of the `size` attribute is usage for vectors, or other heap-backed types, which we want to serialize in Solana accounts. Therefore, providing an arbitrary size is necessary.
=> fix(macros): Don't include original type size when `size` attribute is used

Cargo.lock, Cargo.toml, examples/name-service/programs/name-service/Cargo.toml, js/compressed-token/src/idl/light_compressed_token.ts, js/stateless.js/src/idls/account_compression.ts, js/stateless.js/src/idls/light_compressed_token.ts, js/stateless.js/src/idls/light_registry.ts, js/stateless.js/src/idls/light_system_program.ts, scripts/release-all-rust-crates.sh
* rust crates have been released
* upgrade dependencies to v1.18.22. this is the earliest non-yanked version for v1.x compatibility.
=> chore: release 0.6.0

Cargo.lock, forester-spec.yaml, forester/.dockerignore, forester/.env.example, forester/.gitignore, forester/Cargo.toml, forester/Dockerfile, forester/alert_rules.yml, forester/alertmanager.yml, forester/docker-compose.yml, forester/package.json, forester/prometheus.yml, forester/src/config.rs, forester/src/epoch_manager.rs, forester/src/errors.rs, forester/src/lib.rs, forester/src/main.rs, forester/src/metrics.rs, forester/src/pubsub_client.rs, forester/src/send_transaction.rs, forester/src/settings.rs, forester/src/slot_tracker.rs, forester/src/telemetry.rs, forester/src/utils.rs, forester/tests/e2e_test.rs, forester/tests/test_utils.rs, js/compressed-token/src/idl/light_compressed_token.ts, js/stateless.js/src/idls/light_compressed_token.ts, test-utils/src/forester_epoch.rs, test-utils/src/rpc/solana_rpc.rs
Added:
• Tracing-based telemetry
• Prometheus metrics sender
• Prometheus + AlertManager + PushGateway + Grafana docker-compose configuration
=> feat: forester alerts + monitoring

forester/src/epoch_manager.rs, forester/src/rollover/operations.rs, forester/tests/e2e_test.rs, forester/tests/test_utils.rs, test-programs/registry-test/tests/tests.rs, test-utils/src/e2e_test_env.rs
Issue:
- foresters only check once per active phase for every tree whether it can be rolledover, for long epochs with high traffic this is insufficient
Changes:
- check whether a tree can be rolledover once per light slot
- move rollover  into `process_queue`
- modify test to test a rollover
=> chore: added rollover logic to forester(once per slot) and test

Cargo.lock, forester-utils/src/rpc/solana_rpc.rs, forester/Cargo.toml, forester/src/config.rs, forester/src/epoch_manager.rs, forester/src/lib.rs, forester/src/main.rs, forester/src/metrics.rs, forester/src/photon_indexer.rs, forester/src/pubsub_client.rs, forester/src/queue_helpers.rs, forester/src/rollover/operations.rs, forester/src/send_transaction.rs, forester/src/settings.rs, forester/src/slot_tracker.rs, forester/src/telemetry.rs, forester/src/tree_data_sync.rs, forester/src/utils.rs, forester/tests/test_utils.rs
* Replaced the `log` crate with `tracing` for improved structured logging. 
* Adjusted dependencies in `Cargo.toml` and removed `log` crate.
=> refactor: forester: switch logging from `log` to `tracing`

examples/name-service/programs/name-service/src/lib.rs, examples/name-service/programs/name-service/tests/test.rs, examples/token-escrow/programs/token-escrow/src/escrow_with_compressed_pda/escrow.rs, examples/token-escrow/programs/token-escrow/src/escrow_with_compressed_pda/sdk.rs, examples/token-escrow/programs/token-escrow/src/escrow_with_compressed_pda/withdrawal.rs, examples/token-escrow/programs/token-escrow/src/lib.rs, js/compressed-token/src/idl/light_compressed_token.ts, js/stateless.js/src/idls/light_compressed_token.ts, js/stateless.js/src/idls/light_system_program.ts, merkle-tree/hash-set/src/lib.rs, programs/compressed-token/src/process_mint.rs, programs/compressed-token/src/process_transfer.rs, programs/system/src/invoke_cpi/instruction.rs, programs/system/src/invoke_cpi/process_cpi_context.rs, programs/system/src/invoke_cpi/processor.rs, programs/system/src/invoke_cpi/verify_signer.rs, sdk/src/utils.rs, test-programs/system-cpi-test/src/create_pda.rs, test-programs/system-cpi-test/src/invalidate_not_owned_account.rs, test-programs/system-cpi-test/src/sdk.rs, test-programs/system-cpi-test/tests/test.rs
Issue:
- informational suggestion in two audits  to remove custom signer seeds from invoke cpi
Changes:
- remove signer seeds from `InvokeCpiInstructionData`
- enforce default seed `cpi-authority`  instead of custom seeds
=> fix: remove custom signer seeds from invoke_cpi

.cargo/config.toml, Cargo.toml, examples/name-service/programs/name-service/src/lib.rs, examples/name-service/programs/name-service/tests/test.rs, examples/token-escrow/programs/token-escrow/src/escrow_with_compressed_pda/escrow.rs, examples/token-escrow/programs/token-escrow/src/escrow_with_compressed_pda/withdrawal.rs, examples/token-escrow/programs/token-escrow/src/escrow_with_pda/escrow.rs, macros/light/src/accounts.rs, macros/light/src/lib.rs, macros/light/src/program.rs, sdk/src/compressed_account.rs, sdk/src/context.rs, sdk/src/lib.rs, sdk/src/merkle_context.rs, sdk/src/program_merkle_context.rs, sdk/src/utils.rs, sdk/src/verify.rs
Add the following macros:
- `#[light_program]` - wraps the program module and adds necessary code to the instruction functions.
- `#[light_accounts]` - wraps the instruction struct containing both the regular Anchor accounts and compressed accounts.
See the `name-server` example for the usage.
Related changes:
- Introduce `LightContext` - a new context type which contains `accounts` (regular) and `light_accounts` (compressed). It abstracts away the UTXO model from users, allowing to modify compressed accounts the same way as regular ones.
- Rename the former `#[light_accounts]` macro to `#[light_system_accounts]`.
=> feat: Add macros for compressed PDAs

js/stateless.js/src/idls/account_compression.ts, pnpm-lock.yaml, scripts/devenv.sh
If we try to run: `git clean -dfx && ./scripts/install.sh && . ./scripts.devenv.sh && ./scripts/build.sh` we'll get an error (see below), and then the second call ./scripts/build.sh will run without any errors. This PR fixes this first cargo metadata error on the first build attempt.
```
./scripts/build.sh 
+ pnpm install
Scope: all 12 workspace projects
Lockfile is up to date, resolution step is skipped
Already up to date
cli postinstall$ [ -d ./bin ] && find ./bin -type f -exec chmod +x {} + || echo 'No bin directory found, skipping chmod'
│ No bin directory found, skipping chmod
└─ Done in 11ms
Done in 1s
+ '[' '!' -f target/deploy/spl_noop.so ']'
+ mkdir -p target/deploy
+ cp third-party/solana-program-library/spl_noop.so target/deploy
+ npx nx run-many --target=build --all
NX …
```
=> chore: fix cargo metadata error on first use of build.sh

forester-utils/src/rpc/solana_rpc.rs, forester/src/slot_tracker.rs
Eliminate redundant debug statements in SlotTracker's update method and Solana RPC's get_slot function for cleaner code and potentially improved performance.
=> refactor: forester: remove debug logging from SlotTracker and Solana RPC

light-prover/prover/inclusion_circuit.go
Issue:
- inclusion circuit import setup doesn't assign Merkle proof correctly
Changes:
- assign Merkle proof arrays in loop
- go auto format
=> fix: light prover inclusion setup import

forester/src/cli.rs, forester/src/config.rs, forester/src/epoch_manager.rs, forester/src/main.rs, forester/src/settings.rs, forester/tests/test_utils.rs
Added a new CLI flag, `enable_metrics`, to control metrics reporting. Updated configuration initialization and relevant components to respect this flag, ensuring metrics are processed and pushed conditionally based on user input.
=> feat: forester: enable optional metrics reporting via CLI flag

Cargo.lock, forester/Cargo.toml, forester/src/epoch_manager.rs, forester/tests/e2e_test.rs
Consolidate repeated active phase work processing into a new function `process_epoch_work`. 
Introduce `register_for_epoch_with_retry` to handle registration retries with a specified maximum number of attempts and delay duration.
=> refactor: forester: add retry logic for epoch registration

Cargo.lock, forester/Cargo.toml, forester/src/epoch_manager.rs, forester/tests/e2e_test.rs, test-programs/registry-test/Cargo.toml, test-programs/registry-test/tests/tests.rs
1. Fixed epoch recovery.
2. Introduced a new test to ensure the continuity of the active phase in different protocol configurations.
=> fix: forester: epoch recovery

forester/src/epoch_manager.rs
* Do not check phases for wait_for_active_phase
* Handle report_work transaction errors gracefully in Epoch Manager
=> refactor: forester: add trees in wait_for_active_phase for recovery + don't retry to send report tx if already sent

photon-api/src/apis/default_api.rs
Eliminate verbose info logging for URI and request data to reduce clutter.
=> chore: photon-api: remove excessive logging in default_api.rs

forester/src/epoch_manager.rs, forester/src/slot_tracker.rs
Refactored the rollover check into a separate asynchronous function to improve concurrency in transaction processing.
=> refactor: async rollover

forester/src/epoch_manager.rs, forester/src/send_transaction.rs
Improve timeout handling in epoch manager to prevent overflow errors. 
Introduce a checked multiplication for slot duration and update retry timeout accordingly. 
Additionally, modify transaction handling to break early based on calculated slot latency.
=> refactor: forester: safetys check to minimise non-eligibility + other safety checks

cli/src/utils/constants.ts, js/stateless.js/src/actions/create-account.ts, js/stateless.js/src/rpc-interface.ts, js/stateless.js/src/rpc.ts, js/stateless.js/src/test-helpers/test-rpc/test-rpc.ts, js/stateless.js/tests/e2e/compress.test.ts, js/stateless.js/tests/e2e/rpc-interop.test.ts, scripts/install.sh
uses getValidityProofV0 in createAccount action, ie included in test coverage
=> chore: photon 0.45.0, add: getValidityProofV0 for custom tree support

forester/src/tree_finder.rs
Inserting a yield_now call ensures the task scheduler gets a chance to run other tasks, improving the overall system responsiveness.
=> fix: add yield_now call in tree_finder loop

examples/name-service/programs/name-service/src/lib.rs, macros/light-sdk-macros/src/accounts.rs, macros/light-sdk-macros/src/program.rs, sdk/src/error.rs, sdk/src/lib.rs
Similarly to Anchor's `constraint =` attribute, it can be used to ensure constraints for the given accounts. The constraint can use both regular and compressed accounts.
The most common use-case for it is ensuring the equality of public keys across regular and compressed accounts for security checks.
DNS example is updated to use it for ensuring that compressed `NameRecord` accounts can be modified only by original signers, with `constraint = record.owner == signer.key()`.
=> feat: Add `constraint =` attribute to `#[light_accounts]` macro

forester-utils/src/address_merkle_tree_config.rs, js/stateless.js/src/actions/create-account.ts, js/stateless.js/src/test-helpers/test-rpc/test-rpc.ts, js/stateless.js/tests/e2e/compress.test.ts, js/stateless.js/tests/e2e/rpc-interop.test.ts, merkle-tree/hash-set/src/lib.rs, merkle-tree/hash-set/src/zero_copy.rs, programs/account-compression/src/instructions/rollover_address_merkle_tree_and_queue.rs, programs/account-compression/src/instructions/rollover_state_merkle_tree_and_queue.rs, test-programs/account-compression-test/tests/merkle_tree_tests.rs, test-utils/src/address_tree_rollover.rs, test-utils/src/assert_queue.rs, test-utils/src/state_tree_rollover.rs, test-utils/src/test_forester.rs
Issue:
- HashSet capacity can be unsafely set
Changes:
- change hash set field capacity from pub to private and add a getter
=> fix: hash-set capacity pub -> private

.github/workflows/light-examples-tests.yml, macros/light-sdk-macros/src/accounts.rs
Instead of a manual loop, use `.find()` and `.map()`.
=> refactor: Simplify the check for `light_account` attribute

examples/name-service/programs/name-service/src/lib.rs, macros/light-sdk-macros/src/accounts.rs, macros/light-sdk-macros/src/program.rs
Allow to reference the instruction parameters in `seed =` and `constraint =` parametes inside `light_account` attribute by exposing them through `#[instruction]` attribute. It works the same way as in Anchor.
Code example:
```rust
#[instruction(name: String)]
pub struct MyInstruction {
#[light_account(init, seeds = [b"my-seed", name.as_bytes()])]
pub my_cpda: MyCpdaType,
[...]
}
```
=> feat: Add `#[instruction]` attribute

forester/src/epoch_manager.rs
We need it for the theoretical case: if the rpc pool is busy (CPU congestion), we might miss the registration for the next epoch.
=> refactor: forester: switch to SolanaRpcConnection for epoch registration & work submission.

examples/name-service/programs/name-service/src/lib.rs, macros/light-sdk-macros/src/program.rs
Even when using `idl-build` feature, Anchor still parses the code of the program and expects the `#[program]` attribute applied on the main module.
Before this change, annotating the program module only with `#[light_program]` was preventing the IDL generation. Fix that by requiring both attributes:
```rust
#[light_program]
#[program]
```
And not injecting the `#[program]` inside `#[light_program]`.
=> fix: IDL generation in programs using light-sdk

merkle-tree/hasher/Cargo.toml, merkle-tree/hasher/src/bytes.rs, merkle-tree/hasher/src/errors.rs
We were inconsistently using `#[cfg(feature = "solana")]` and `#[cfg(target_os = "solana")]` in different places, which was leading to issues when some third-party crate was using `light-hasher` without `solana` feature, but in sBPF environment.
This feature is a footgun and there is no real benefit of not using solana-program as a dependency, so just stop using it.
The `solana` feature is stil listed in `Cargo.toml`, but doesn't do anything. That's because there are still crates depending on that feature. We can remove it once we are ready to affect them.
=> fix: Use `solana-program` in `light-hasher` indiscriminately

.github/workflows/light-examples-tests.yml, sdk/src/address.rs, sdk/src/compressed_account.rs, sdk/src/event.rs, sdk/src/proof.rs, sdk/src/state.rs, sdk/src/token.rs, sdk/src/verify.rs
Using Borsh traits directly (`BorshDeserialize`, `BorshSerialize`) instead of the Anchor variants doesn't play well with idl-build.
=> fix: Use `AnchorDeserialize`/`AnchorSerialize` instead of borsh directly

cli/.npmignore, cli/package.json, pnpm-lock.yaml
issue:
- `cargo-generate` bin was bundled accidentally with release of cli this way the cli release `0.18.0` init command only works for mac os without manually removing the bundled `cargo-generate` binary
Changes:
- bump cli version to `0.18.1`
- add `.npmignore` file to remove the footgun of accidentally bundling `cargo-generate`
=> chore: bump cli version and add .npmignore

examples/name-service/programs/name-service/tests/test.rs, js/stateless.js/src/actions/create-account.ts, js/stateless.js/src/utils/address.ts, js/stateless.js/src/utils/conversion.ts, js/stateless.js/tests/e2e/compress.test.ts, js/stateless.js/tests/e2e/rpc-interop.test.ts, macros/light-sdk-macros/src/accounts.rs, sdk/src/address.rs
**Problems**
- The distinction between `derive_address_seed` and `derive_address` was
unclear and we were inconsistent in it:
- We ended up applying address Merkle tree public key in both
functions, which is confusing.
- Before this change, there was no TypeScript function for deriving
**address seed**. There was only `deriveAddress`, but deriving the
unified seed was a mystery for developers.
- We have two utilities for hashing and truncating to BN254:
- `hash_to_bn254_field_size_be` - the older one, which:
- Searches for a bump in a loop, adds it to the hash inputs and then
truncates the hash. That doesn't make sense, because truncating
the hash should be sufficient, adding a bump is unnecessary.
- Another limitation is that it takes only one sequence of bytes,
making it difficult to …
=> refactor: `deriveAddressSeed` and `deriveAddress` utilities

Cargo.lock, Cargo.toml, macros/light-sdk-macros/Cargo.toml, sdk/Cargo.toml
note: cli init does not yet use the new sdk release. awaiting program-template update
=> chore: bump sdk 0.11.0, sdk-macros 0.4.0

scripts/build.sh, scripts/devenv.sh
If we run build.sh we'll get an error:
`./scripts/build.sh: 64: ./scripts/devenv.sh: [[: not found`
This PR fixes it.
=> fix: switch to bash in build and devenv scripts

cli/package.json, cli/src/utils/process.ts, pnpm-lock.yaml
`port` is a `number`. Using it in command construction is safe.
=> chore(cli): Supress the CodeQL shell-command error

cli/src/utils/process.ts
Previously, the code only checked for an exact match of the process name, but now it also checks for partial matches in the process name or command.
=> refactor: cli: improve process killing logic

cli/README.md, cli/package.json, cli/src/utils/constants.ts, js/compressed-token/README.md, js/compressed-token/package.json, js/compressed-token/tests/e2e/rpc-token-interop.test.ts, js/stateless.js/README.md, js/stateless.js/package.json, js/stateless.js/src/rpc-interface.ts, js/stateless.js/src/rpc.ts, js/stateless.js/src/test-helpers/test-rpc/test-rpc.ts, scripts/install.sh
+ extends endpoints with opt. cursors, non-breaking
+ adds --no-reset flag to install.sh
+ cleans up the js readmes
=> feat: bump to 0.50.0, add getCompressedTokenBalancesByOwnerV2

js/compressed-token/README.md, js/compressed-token/tests/e2e/rpc-token-interop.test.ts, programs/compressed-token/src/lib.rs, programs/compressed-token/src/process_compress_spl_token_account.rs, programs/compressed-token/src/process_transfer.rs, scripts/format.sh, test-programs/compressed-token-test/tests/test.rs, test-utils/src/spl.rs
- add instruction to compress a spl token account with an optional remaining amount
- `process_compress_spl_token_account`
- creates an `compressed_output_account`
- wraps `process_transfer`
- moved instruction data deserialization out of  `process_transfer` so that `process_compress_spl_token_account` can wrap it
=> feat: compress spl token account

js/compressed-token/src/idl/light_compressed_token.ts, js/stateless.js/src/idls/light_compressed_token.ts, programs/compressed-token/src/lib.rs, programs/compressed-token/src/process_compress_spl_token_account.rs, test-programs/compressed-token-test/tests/test.rs
**Changes:**
1. add doc string to compress_spl_token_account
2. replace ArithmeticUnderflow error with InsufficientTokenAccountBalance
3. add failing test InsufficientTokenAccountBalance
=> chore: compress spl token audit informational fixes 

cli/src/commands/compress-spl/index.ts, cli/src/commands/decompress-spl/index.ts, js/compressed-token/src/actions/approve-and-mint-to.ts, js/compressed-token/src/actions/compress-spl-token-account.ts, js/compressed-token/src/actions/compress.ts, js/compressed-token/src/actions/create-mint.ts, js/compressed-token/src/actions/create-token-pool.ts, js/compressed-token/src/actions/decompress.ts, js/compressed-token/src/actions/merge-token-accounts.ts, js/compressed-token/src/actions/mint-to.ts, js/compressed-token/src/program.ts, js/compressed-token/tests/e2e/approve-and-mint-to.test.ts, js/compressed-token/tests/e2e/compress-spl-token-account.test.ts, js/compressed-token/tests/e2e/compress.test.ts, js/compressed-token/tests/e2e/transfer.test.ts, pnpm-lock.yaml
**Issue:**
- ts sdk is missing token 2022 support
**Changes:**
- add optional token program id for create instruction functions
-  fetch token program id if not provided for actions
- fetch token mint and determine owner in cli methods compress and decompress to determine token program id for ata derivation
**Tests Coverage:**
- create token pool
- mint to
- transfer
- compress
- decompress
- approve and mint to
=> feat: ts-sdk token 2022 support

cli/package.json, cli/src/commands/test-validator/index.ts, cli/src/utils/initTestEnv.ts, cli/src/utils/processPhotonIndexer.ts, cli/test/commands/test-validator/index.test.ts
This allows adding SBF programs to the genesis configuration with upgrades disabled. The flag accepts pairs of arguments (address and path) to specify programs, and validates input to ensure correct usage.
=> feat: add support for `--sbf-program` flag in test-validator

client/tests/rpc_client.rs, examples/token-escrow/programs/token-escrow/src/escrow_with_pda/sdk.rs, js/compressed-token/src/idl/light_compressed_token.ts, js/stateless.js/src/idls/light_compressed_token.ts, pnpm-lock.yaml, programs/compressed-token/src/burn.rs, programs/compressed-token/src/constants.rs, programs/compressed-token/src/instructions/burn.rs, programs/compressed-token/src/instructions/create_token_pool.rs, programs/compressed-token/src/lib.rs, programs/compressed-token/src/process_compress_spl_token_account.rs, programs/compressed-token/src/process_mint.rs, programs/compressed-token/src/process_transfer.rs, programs/compressed-token/src/spl_compression.rs, test-programs/compressed-token-test/tests/test.rs, test-programs/system-cpi-test/tests/test_program_owned_trees.rs, test-utils/src/assert_token_tx.rs, test-utils/src/e2e_test_env.rs, test-utils/src/spl.rs
- the compress token program allows only one `tokenPoolPda` account to be created per token mint
- this causes a single shared write-lock for all tokens of a mint that get compressed or decompressed
- enable multiple `tokenPoolPda` accounts per mint
- don't allow too many accounts so that users can still decompress from all token pool accounts in one instruction if required
- as of this pr, the maximum of token pool accounts per mint is 5
- add instruction `add_token_pool`
- adapt `spl_token_pool_derivation` with a bump to derive multiple accounts
- for spl token compression loop over possible derivations until we find the correct one
- for spl token decompression, if the balance of the first `tokenPoolPda` is insufficient to support the decompression amount, loop over remaining accounts …
=> feat: multiple `tokenPoolPda` accounts

merkle-tree/concurrent/tests/tests.rs
`https://docs.aztec.network/concepts/advanced/data_structures/indexed_merkle_tree` - `https://docs.aztec.network/aztec/concepts/storage/trees/indexed_merkle_tree`
=> fix: broken link tests.rs

light-prover/scripts/download_keys.sh
mac does not have `sha256sum` installed by default. this causes `install.sh` to throw when checking proving keys on Mac
solution:
fallback to `shasum` if `sha256sum` isn't installed
=> fix: fallback to mac-compatible shasum command in `download_keys.sh`

prover/server/integration_test.go, prover/server/prover/batch_address_append_circuit.go, prover/server/prover/batch_address_append_circuit_test.go, prover/server/prover/batch_append_with_proofs_circuit.go, prover/server/prover/batch_append_with_proofs_circuit_test.go, prover/server/prover/batch_update_circuit_test.go, prover/server/prover/marshal_batch_address_append.go, prover/server/prover/marshal_batch_append_with_proofs.go, prover/server/prover/test_data_helpers.go
1. Added negative test cases for batch update circuit, batch append with proofs and batch address append circuits.
2. Update startIndex to uint64.
=> refactor: batch circuits

Cargo.lock, Cargo.toml
Issue:
- broken name-service example program prevents osec-api to recompile and verify latest compressed token program deployment
Changes:
- remove name-service example from project Cargo.toml until it is fixed
=> chore: remove name-service example from project Cargo.toml

sdk-libs/macros/src/program.rs
The typo in the word "accounds" has been fixed to "accounts" in the following line:
// - The struct with compressed accounts (implementing `LightAccounts`) -  
Thank you
=> fix typo Update program.rs

forester/src/send_transaction.rs
TIMEOUT_CHECK_ENABLED is needed when multiple foresters are working simultaenously, otherwise there is high probability of case when forester will try to send transactions when its not eligible.
=> fix: enable timeout check in transaction builder

forester-utils/src/instructions.rs, forester/tests/batched_address_test.rs, forester/tests/batched_state_test.rs, program-libs/batched-merkle-tree/src/batch.rs, program-libs/batched-merkle-tree/src/batch_metadata.rs, program-libs/batched-merkle-tree/src/event.rs, program-libs/batched-merkle-tree/src/initialize_state_tree.rs, program-libs/batched-merkle-tree/src/merkle_tree.rs, program-libs/batched-merkle-tree/src/queue.rs, program-libs/batched-merkle-tree/src/rollover_address_tree.rs, program-libs/batched-merkle-tree/tests/merkle_tree.rs, program-libs/verifier/src/lib.rs, program-tests/account-compression-test/tests/batched_merkle_tree_test.rs, program-tests/system-test/tests/test.rs, programs/system/src/invoke/verify_state_proof.rs, programs/system/src/invoke_cpi/process_cpi_context.rs, programs/system/src/sdk/mod.rs, prover/client/src/mock_batched_forester.rs, sdk-libs/program-test/src/test_batch_forester.rs, sdk-libs/sdk/src/verify.rs
Changes:
1. rename `BatchState::CanBeFilled` -> `BatchState::Fill`
2. rename `*_wiped` -> `*_zeroed`
3. initializing root history with full length
-> needed to adapt expected len assertion in batched forester tests 
4.
=> chore: cleanup & fix zero out bloom filter

Cargo.lock, program-libs/batched-merkle-tree/Cargo.toml, program-libs/batched-merkle-tree/src/merkle_tree.rs, program-libs/batched-merkle-tree/src/queue.rs, program-libs/batched-merkle-tree/tests/rollover_state_tree.rs, program-libs/zero-copy/Cargo.toml, program-libs/zero-copy/src/cyclic_vec.rs, program-libs/zero-copy/src/errors.rs, program-libs/zero-copy/src/lib.rs, program-libs/zero-copy/src/slice_mut.rs, program-libs/zero-copy/src/vec.rs, program-libs/zero-copy/tests/cyclic_vec_tests.rs, program-libs/zero-copy/tests/slice_mut_test.rs, program-libs/zero-copy/tests/vec_tests.rs
changes:
1. make light-zero-copy no-std (default features includes std because we use vec for testing)
2. increase code coverage
3. improve zerocopy -> light-zero-copy error conversion
=> chore: make light-zero-copy no-std, increase test coverage

program-libs/batched-merkle-tree/src/rollover_address_tree.rs, program-libs/batched-merkle-tree/src/rollover_state_tree.rs, programs/account-compression/src/instructions/rollover_batched_address_merkle_tree.rs, programs/account-compression/src/instructions/rollover_batched_state_merkle_tree.rs
Changes:
- move rollover checks from account compression program into light-batched-merkle-tree wrapper functions `*_from_account_info`
=> chore: move rollover completely into batched crate

Cargo.lock, forester/src/cli.rs, forester/src/config.rs, forester/src/epoch_manager.rs, forester/src/lib.rs, forester/src/main.rs, forester/tests/batched_address_test.rs, forester/tests/batched_state_test.rs, forester/tests/e2e_test.rs, forester/tests/priority_fee_test.rs, forester/tests/test_utils.rs, program-tests/account-compression-test/tests/address_merkle_tree_tests.rs, program-tests/account-compression-test/tests/batched_merkle_tree_test.rs, program-tests/account-compression-test/tests/group_authority_tests.rs, program-tests/account-compression-test/tests/merkle_tree_tests.rs, program-tests/registry-test/tests/tests.rs, program-tests/system-test/tests/test.rs, programs/registry/src/utils.rs, sdk-libs/client/Cargo.toml, sdk-libs/client/src/indexer/photon_indexer.rs, sdk-libs/client/src/lib.rs, sdk-libs/client/src/photon_rpc/photon_client.rs, sdk-libs/client/src/rate_limiter.rs, sdk-libs/client/src/rpc/rpc_connection.rs, sdk-libs/client/src/rpc/solana_rpc.rs, sdk-libs/client/src/rpc_pool.rs, sdk-libs/program-test/src/test_env.rs, sdk-libs/program-test/src/test_rpc.rs
Implemented rate limiter for rpc calls.
Forester can be run with 3 optional flags:
```
--rpc-rate-limit <RPC_RATE_LIMIT>
--photon-rate-limit <PHOTON_RATE_LIMIT>
--send-tx-rate-limit <SEND_TX_RATE_LIMIT>
```
=> feat: rate limiter

program-libs/batched-merkle-tree/src/merkle_tree.rs, program-libs/batched-merkle-tree/tests/initialize_address_tree.rs, program-libs/batched-merkle-tree/tests/rollover_address_tree.rs, program-libs/merkle-tree-metadata/src/errors.rs, programs/system/src/processor/cpi.rs
Issue:
- address tree init root value is hardcoded for height 40
-> add a check for address tree height in non test environments
=> chore: add address tree height error

.gitignore, Cargo.lock, program-libs/compressed-account/src/event.rs, program-libs/compressed-account/src/instruction_data/zero_copy.rs, program-libs/zero-copy/src/borsh.rs, program-tests/compressed-token-test/tests/test.rs, programs/system/src/processor/process.rs, scripts/export-photon-test-transactions.sh, xtask/Cargo.toml, xtask/src/export_photon_test_data.rs, xtask/src/main.rs
Changes:
1. add xtask which exports transactions as json readable by photon tests from a running test ledger into a folder in target 
2. add a compressed token test to generate token test data in a batched tree
3. add a script to generate test data from forester test and compressed token test
4. `event_from_light_transaction` replace zero copy deserialization of system program instruction with borsh deserialization
5. replace relayer_fee unimplemented with error
=> feat: add generate photon test data script

sdk-libs/sdk/src/verify.rs
Renamed `accounts_metas` parameter to `account_metas` in invoke_cpi function to align with standard Solana naming conventions for AccountMeta collections.
=> Fix parameter naming in invoke_cpi to match Solana conventions

examples/anchor/counter/tests/test.rs, examples/anchor/memo/tests/test.rs, examples/anchor/name-service-without-macros/tests/test.rs, examples/anchor/name-service/tests/test.rs, examples/anchor/token-escrow/src/escrow_with_compressed_pda/escrow.rs, examples/anchor/token-escrow/src/escrow_with_compressed_pda/withdrawal.rs, program-libs/batched-merkle-tree/src/queue.rs, program-tests/sdk-anchor-test/programs/sdk-anchor-test/Cargo.toml, program-tests/sdk-anchor-test/programs/sdk-anchor-test/src/lib.rs, program-tests/sdk-anchor-test/programs/sdk-anchor-test/tests/test.rs, program-tests/sdk-test/src/create_pda.rs, program-tests/sdk-test/src/lib.rs, program-tests/sdk-test/src/update_pda.rs, program-tests/sdk-test/tests/test.rs, sdk-libs/sdk/src/account.rs, sdk-libs/sdk/src/account_info.rs, sdk-libs/sdk/src/account_meta.rs, sdk-libs/sdk/src/address.rs, sdk-libs/sdk/src/error.rs, sdk-libs/sdk/src/instruction_data.rs, sdk-libs/sdk/src/lib.rs, sdk-libs/sdk/src/merkle_context.rs, sdk-libs/sdk/src/program_merkle_context.rs, sdk-libs/sdk/src/system_accounts.rs, sdk-libs/sdk/src/transfer.rs, sdk-libs/sdk/src/verify.rs
- rename `RemainingAccounts` -> `CpiAccounts`
- rename `verify` ->  `verify_borsh` , pull in signer seeds and generate bump seed at compile time in `invoke_light_system_program`
- remove `verify_light_accounts` instead we can do `CAccount.to_account_info()` and use `verify_light_account_infos`
- rename LightAccountInfo -> `CAccountInfo`, split it into `CInAccountInfo` and `COutAccountInfo` for cheaper zero copy
- removed options for lamports for cheaper zero copy
- note that `CAccountInfo` will need to move into `light-compressed-account` once we add the pda optimized system program instruction
- `SystemInfoInstructionData` is unused
-  split up `LightAccountMeta` into 4 specialized structs:
1. InputAccountMeta (context, address, root_index, output_merkle_tree_index)
(A pda with address, …
=> refactor: light-sdk, Light Account and LightAccountInfo

Cargo.lock, program-libs/compressed-account/src/indexer_event/event.rs, program-libs/compressed-account/src/indexer_event/parse.rs, program-tests/system-cpi-test/tests/event.rs
1. Introduce a `queue_index` field in the `NewAddress` struct and update its handling in the `parse.rs` logic.
2. Added the `create_address_queue_indices` function to compute queue indices for new addresses, aligning with the existing pattern for nullifier queue indices.
3. Additionally, include a sanity check to validate queue indexing for new addresses.
=> feat: add `queue_index` to `NewAddress` and implement handling logic

Cargo.lock, examples/anchor/counter/src/lib.rs, examples/anchor/memo/src/lib.rs, examples/anchor/name-service-without-macros/src/lib.rs, program-libs/account-checks/src/checks.rs, program-libs/account-checks/src/discriminator.rs, program-libs/batched-merkle-tree/src/merkle_tree.rs, program-libs/batched-merkle-tree/src/queue.rs, program-libs/hasher/src/lib.rs, program-tests/sdk-anchor-test/programs/sdk-anchor-test/Cargo.toml, program-tests/sdk-anchor-test/programs/sdk-anchor-test/src/lib.rs, program-tests/sdk-test/Cargo.toml, program-tests/sdk-test/src/create_pda.rs, programs/system/src/invoke_cpi/account.rs, programs/system/src/invoke_cpi/instruction.rs, programs/system/src/invoke_cpi/small_accounts.rs, sdk-libs/macros/src/discriminator.rs, sdk-libs/sdk/Cargo.toml, sdk-libs/sdk/src/account.rs, sdk-libs/sdk/src/lib.rs
**changes:**
1. refactor discriminator sdk macro to implement `Discriminator` instead of `light_hasher::Discriminator`
2. light-hasher remove Discriminator
3. light-account-checks remove constant from Discriminator
3.1. adapt batched Merkle tree impl of Discriminator trait
=> refactor: unify Discriminator traits

examples/anchor/counter/src/lib.rs, examples/anchor/memo/src/lib.rs, examples/anchor/name-service-without-macros/src/lib.rs, program-libs/compressed-account/src/instruction_data/with_account_info.rs, sdk-libs/sdk/src/account.rs, sdk-libs/sdk/src/account_info.rs, sdk-libs/sdk/src/cpi/verify.rs, sdk-libs/sdk/src/transfer.rs
Changes:
1. rename `from_meta_mut` -> `meta_mut`
2. rename `CAccountInfo` -> `CompressedAccountInfo`
3. remove `light-sdk` implementations and import from `light-compressed-account` instead 
3.1. `SystemInfoInstructionData`
3.2. `InAccountInfo`
3.3. `OutAccountInfo`
4. create `AccountInfoTrait` in `light-sdk` so that I don't need to implement sdk methods in `light-compressed-account`
5. create `InAccountInfoTrait` in `light-sdk` so that I don't need to implement sdk methods in `light-compressed-account`
=> refactor: sdk use compressed account info from light-compressed-account

examples/anchor/token-escrow/tests/test.rs, examples/anchor/token-escrow/tests/test_compressed_pda.rs, program-libs/compressed-account/src/compressed_account.rs, program-libs/compressed-account/src/instruction_data/with_readonly.rs, program-libs/compressed-account/src/instruction_data/zero_copy.rs, program-tests/compressed-token-test/tests/test.rs, program-tests/system-cpi-test/src/create_pda.rs, program-tests/system-cpi-test/tests/event.rs, program-tests/system-cpi-test/tests/test.rs, program-tests/system-test/tests/test.rs, program-tests/utils/src/assert_compressed_tx.rs, program-tests/utils/src/system_program.rs, programs/compressed-token/src/burn.rs, programs/compressed-token/src/delegation.rs, programs/compressed-token/src/freeze.rs, programs/compressed-token/src/process_transfer.rs, programs/system/src/processor/create_inputs_cpi_data.rs, programs/system/src/processor/read_only_account.rs, programs/system/src/processor/sum_check.rs, scripts/format.sh, sdk-libs/client/src/indexer/mod.rs, sdk-libs/client/src/indexer/photon_indexer.rs, sdk-libs/program-test/src/indexer/test_indexer.rs, sdk-libs/sdk/src/instruction/merkle_context.rs, sdk-libs/sdk/src/transfer.rs
Changes:
1. `MerkleContext` `nullifier_queue_pubkey` -> `queue_pubkey`
2. `PackedMerkleContext` `nullifier_queue_pubkey_index` -> `queue_pubkey_index`
=> refactor: merkle context nullifier to queue pubkey

.github/workflows/light-examples-tests.yml, Cargo.lock, Cargo.toml, examples/anchor/counter/src/lib.rs, examples/anchor/counter/tests/test.rs, program-tests/sdk-anchor-test/programs/sdk-anchor-test/src/lib.rs, program-tests/sdk-test/src/create_pda.rs, program-tests/sdk-test/src/update_pda.rs, sdk-libs/sdk/src/account.rs
Changes:
1. adapt counter example to new sdk
2. add close instruction to counter example
3. renamed `CBorshAccount` -> `LightAccount`
=> refactor: counter example

program-libs/compressed-account/src/address.rs, program-libs/compressed-account/src/instruction_data/data.rs, program-libs/compressed-account/src/instruction_data/traits.rs, program-libs/compressed-account/src/instruction_data/with_account_info.rs, program-libs/compressed-account/src/instruction_data/with_readonly.rs, program-libs/compressed-account/src/instruction_data/zero_copy.rs, program-tests/system-cpi-test/src/create_pda.rs, program-tests/system-cpi-test/tests/event.rs, program-tests/utils/src/e2e_test_env.rs, programs/system/src/context.rs, programs/system/src/errors.rs, programs/system/src/invoke_cpi/processor.rs, programs/system/src/lib.rs, programs/system/src/processor/create_address_cpi_data.rs, programs/system/src/processor/create_outputs_cpi_data.rs, programs/system/src/processor/process.rs, programs/system/src/processor/verify_proof.rs, scripts/install.sh, sdk-libs/program-test/src/test_batch_forester.rs
- To ensure that a new address is assigned to a specific compressed output account a program currently needs to derive the address and set it onchain. This results in the address being derived twice once in the program, once in the system program. 
1. extend instruction data for new address params with `assigned_account_index`
- add `NewAddressParamsAssigned` and `NewAddressParamsAssignedPacked`
- diff to `NewAddressParams` is the additional field:   `pub assigned_account_index: Option<u8>`
`None` -> address is not assigned to any account.
`Some(index)` system checks that output account with index X holds the address.
2. compare address derived from new address params with the address of the output account in `assigned_account_index`
- `check_new_address_assignment` 
- functional test …
=> feat: assign addresses

program-libs/compressed-account/src/instruction_data/traits.rs, program-libs/compressed-account/src/instruction_data/with_account_info.rs, program-libs/compressed-account/src/instruction_data/with_readonly.rs, program-libs/compressed-account/src/instruction_data/zero_copy.rs, programs/system/src/context.rs, programs/system/src/invoke_cpi/process_cpi_context.rs, programs/system/src/invoke_cpi/processor.rs, programs/system/src/invoke_cpi/verify_signer.rs, programs/system/src/lib.rs, programs/system/src/processor/create_address_cpi_data.rs, programs/system/src/processor/create_inputs_cpi_data.rs, programs/system/src/processor/create_outputs_cpi_data.rs, programs/system/src/processor/process.rs, programs/system/src/processor/sum_check.rs, programs/system/src/processor/verify_proof.rs
Changes:
1. `InstructionDataTrait` -> `InstructionData`
2. `InputAccountTrait` -> `InputAccount`
3. `OutputAccountTrait` -> `OutputAccount`
4. `NewAddressParamsTrait` -> `NewAddress`
=> chore: rename instruction data traits

forester/package.json, forester/src/epoch_manager.rs
1. Increases log verbosity for key operations in `process_queue` (finding slots, waiting, sending txs) by changing several `trace!` calls to `info!`.
2. Modifies error handling within the main loop:
- Errors encountered during the rollover check (`check_for_epoch_rollover`) are now logged as errors but no longer cause the `process_queue` function to return immediately.
- Failures during `send_batched_transactions` are also logged as errors, but the function now continues processing the epoch instead of returning the error. This makes the forester more resilient to transient transaction send issues.
3. Removes a redundant `TODO` comment.
=> refactor: improve epoch_manager error handling and logging

forester-utils/src/utils.rs, forester/src/epoch_manager.rs, forester/src/slot_tracker.rs, forester/src/smart_transaction.rs, forester/tests/address_v2_test.rs, prover/server/prover/proving_keys_utils.go, sdk-libs/client/src/rpc/solana_rpc.rs, sdk-libs/client/src/rpc_pool.rs, sdk-libs/program-test/src/indexer/test_indexer.rs
* enhance address creation logic to support multiple addresses
* add `tokio::task::yield_now()` in async loops to improve responsiveness
=> feat: address v2 test with multiple addresses, add async yields

program-libs/account-checks/src/checks.rs, program-tests/account-compression-test/tests/batched_merkle_tree_test.rs, sdk-libs/program-test/src/test_batch_forester.rs
Issue:
- an increase in accounts lamports increased the rollover fee
Solution:
- return rent exempt amount instead of account lamports
=> fix: check_account_balance_is_rent_exempt return rent_exemption

.github/actions/setup-and-build-nocheck/action.yml
GitHub runners now default to Node 20; actions/cache@v4 is the recommended version. Only workflow files changed—no functional impact.
=> CI: migrate workflows to cache v4

examples/browser/nextjs/package.json, package.json, pnpm-lock.yaml
Just `pnpm update`. It was needed because dependabot broke compilation of `/examples/browser/nextjs`:
```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: (0 , g.patchFetch) is not a function
at Module.w (/Users/tsv/Developer/light/examples/browser/nextjs/.next/server/chunks/571.js:3:18748)
at az (/Users/tsv/Developer/light/node_modules/.pnpm/next@15.1.6_@babel+core@7.27.1_@playwright+test@1.47.1_react-dom@19.1.0_react@19.1.0__react@19.1.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:131:9349)
at AsyncLocalStorage.run (node:async_hooks:346:14)
at aW (/Users/tsv/Developer/light/node_modules/.pnpm/next@15.1.6_@babel+core@7.27.1_@playwright+test@1.47.1_react-dom@19.1.0_react@19.1.0__react@19.1.0/node_modules/n …
```
=> chore: pnpm update

Cargo.lock, Cargo.toml, sdk-libs/client/Cargo.toml, sdk-libs/client/src/indexer/base58.rs, sdk-libs/client/src/indexer/mod.rs, sdk-libs/client/src/indexer/photon_indexer.rs, sdk-libs/client/src/indexer/tree_info.rs, sdk-libs/client/src/indexer/types.rs, sdk-libs/client/src/rpc/errors.rs, sdk-libs/client/src/rpc/indexer.rs, sdk-libs/client/tests/rpc_client.rs, sdk-libs/program-test/src/indexer/test_indexer.rs, sdk-libs/program-test/src/program_test/indexer.rs, sdk-libs/sdk/src/instruction/merkle_context.rs
1. add `get_compressed_accounts_by_owner`
2. remove vector in base58 to fixed sized array conversion
3. implement `Account` type equivalent to photon indexer `AccountV2`
4. use new `Account` type as return type for `get_compressed_account`
=> fix: indexer get_compressed_account return type

.github/workflows/prover-test.yml, prover/server/Dockerfile.light, prover/server/docker-compose.yml, prover/server/main.go, prover/server/redis_queue_test.go, prover/server/server/queue.go, prover/server/server/queue_job.go, prover/server/server/server.go
- Add specialized queue workers for batch operations
- Add Dockerfile.light without bundled proving keys for faster k8s deployment
- Replace generic queue workers with circuit-specific workers (update, append, address-append)
- Implement separate cleanup routines for old requests (30min) and results (1000+ items)
- Add redis queue tests
- Remove priority system and queue-workers flag in favor of circuit-based routing
- Always route batch operations to queues to prevent cross-contamination
- Enhanced failed job status reporting with detailed error information
- Fix SERVER_MODE environment variable typo
=> feat: specialized queue workers for prover server

.github/workflows/forester-tests.yml, forester/package.json, forester/src/cli.rs, forester/src/config.rs, forester/src/epoch_manager.rs, forester/tests/priority_fee_test.rs, sdk-libs/client/src/rpc/client.rs
Add the ability to select processing mode (v1/v2/all trees) via a new CLI flag.
=> feat: add processor mode selection to forester CLI

forester/src/processor/tx_cache.rs, forester/src/processor/v1/tx_builder.rs, forester/src/queue_helpers.rs
- added timeouts for transaction processing phases and warns about long-running items
- removed unwrap
=> refactor: forester: timeouts & unwrap

forester/tests/test_batch_append_spent.rs
We use this test as snapshot data generator for one of the photon tests. 
See also: https://github.com/helius-labs/photon/pull/292/files#diff-8f9956ca6efda57748cb6801a1e972561da8a2cd355a692815eabd94911b462b
=> test: batch nullify in the queue => batch append spent accs to the tree

Cargo.lock, Cargo.toml, program-libs/indexed-array/Cargo.toml, program-tests/merkle-tree/Cargo.toml, scripts/detect-version-changes.sh, scripts/validate-packages.sh, sparse-merkle-tree/Cargo.toml
This PR bumps versions for program-libs crates.
```
light-indexed-array: 0.1.0 → 0.2.0
light-merkle-tree-reference: 3.0.0 → 3.0.1
```
1. Versions bumped in Cargo.toml files
2. PR validation (dry-run) will run automatically
3. After merge, GitHub Action will publish each crate individually to crates.io and create releases
---
*Generated by `scripts/create-release-pr.sh program-libs`*
=> chore: bump program-libs versions
