- .gitmodules
- light-system-programs/Cargo.lock
- light-system-programs/programs/merkle_tree_program/Cargo.toml
- light-system-programs/programs/verifier_program_one/Cargo.toml
- light-system-programs/programs/verifier_program_storage/Cargo.toml
- light-system-programs/programs/verifier_program_two/Cargo.toml
- light-system-programs/programs/verifier_program_zero/Cargo.toml
- light-verifier-sdk/Cargo.lock
- light-verifier-sdk/Cargo.toml
- mock-app-verifier/Cargo.lock
- mock-app-verifier/programs/verifier/Cargo.toml
There is no need to keep the submodules anymore.
> cargo: Use light-macros and light-merkle-tree from crates.io

- cli/README.md
> Update CLI README.md

- cli/src/utils/downloadBin.ts
> cli: Fix the system/architecture matrix detection

- cli/src/commands/init.ts
no more --name name, just name
> cli: turn explicit flag into positional argument

- .github/workflows/test.yml
> ci: Use buildget Github runner

- cli/package.json
> cli: bumped version to alpha.10

- .gitignore
- light-zk.js/.gitignore
- light-zk.js/src/errors.ts
- light-zk.js/src/transaction/transactionParameters.ts
- light-zk.js/src/utxo.ts
- light-zk.js/tests/account.test.ts
- light-zk.js/tests/balance.test.ts
- light-zk.js/tests/circuits.test.ts
- light-zk.js/tests/convertDecimals.test.ts
- light-zk.js/tests/createOutUtxos.test.ts
- light-zk.js/tests/prover.test.ts
- light-zk.js/tests/provider.test.ts
- light-zk.js/tests/selectInUtxos.test.ts
- light-zk.js/tests/transaction.test.ts
- light-zk.js/tests/transactionParameters.test.ts
- light-zk.js/tests/utxo.test.ts
- light-zk.js/tests/verifiers.test.ts
* removed duplicate tests
* cleaned up warnings
* fixed few typos
> Cleaned up tests.

- README.md
make required use of devenv for tests on ARM explicit
> Update README.md - note for ARM

- cli/README.md
- remove dead commands
- add usage section for overview
- add discord link
- better ux for npmjs (reflinks to repo and docs) (npmjs renders the readme in their preview: https://www.npmjs.com/package/@lightprotocol/cli)
> fix: Update CLI README.md

- light-zk.js/src/transaction/transaction.ts
proof and opt. appProof execute at once now
> perf: parallel proof execution

- cli/package.json
- cli/src/psp-utils/download.ts
- cli/src/utils/initTestEnv.ts
- bumped version for release
- fixed bin path
> fix(cli): bin dir creation path

- .github/actions/setup-and-build/action.yml
- relayer/tests/runTest.sh
- relayer/tests/runTestCli.sh
- scripts/install.sh
Add more retries to ensure that temporary connectivity issues on CI don't impact the setup process.
> build: Fix flakiness of install.sh script

- light-system-programs/tests/user-merge.tests.ts
- increase airdrop amount to fix user merge ci tests
> fix: system programs user merge test increase aidrop amount

- .github/actions/setup-and-build/action.yml
- scripts/build.sh
- scripts/install.sh
Also, ensure that the same one is used in CI.
> chore: Add pnpm to `install.sh` script

- verifier-sdk/src/light_transaction.rs
There were `recipient_mint` and `sender_mint` variables, which despite the name, were just unpacked variants of `recipient_spl` and `sender_spl`. These variables contain the mint as a field, but are not just mints themselves.
> fix(verifier-sdk): Rename misleading `*_mint` variables

- system-programs/tests/merkle_tree_tests.ts
* Before initializing new Merkle Trees:
* Ensure that existing Merkle Trees are marked as the newest ones.
* Ensure that the next Merkle Tree indexes in Merkle Tree Authority are 1.
* After initializing new Merkle Trees:
* Ensure that old Merkle Trees aren't marked as the newest ones anymore.
* Ensure that the new Merkle trees are marked as the newest ones.
* Ensure that the next Merkle Tree indexes in Merkle Tree Authority are 2.
> test(programs): Add more test cases for Merkle Tree initialization

- verifier-sdk/src/light_transaction.rs
Having a logic which decides which Transaction Merkle Tree is being used (the one provided as a remaining account or the one in the context) in a bigger function might be quite error-prone and confusing. Move it to a well commented, separate method.
> refactor(verifier-sdk): Create a method for getting Transaction Merkle Tree

- scripts/test.sh
- source is not compatible with all shells, fix: use "." instead
- move testDockerRelayer.sh to the end of test.sh
> fix: test.sh script

- scripts/build.sh
- thanks @sergeytimoshin for spotting
> fix: build.sh 

- verifier-sdk/src/errors.rs
- verifier-sdk/src/light_transaction.rs
- zk.js/tests/system-programs/functional_tests.ts
- zk.js/tests/system-programs/merkle_tree_tests.ts
- zk.js/tests/system-programs/verifier_tests.ts
Co-authored-by: ananas-block <flow23@protonmail.com>
> fix(verifier-sdk): Check if `spl_sender` is owned by the signer during shields

- .github/workflows/release-pr.yml
- .github/workflows/release.yml
- .github/workflows/tag.yml
- Cargo.lock
- macro-circom/Cargo.toml
- macros/light/Cargo.toml
- programs/merkle-tree/Cargo.toml
- programs/psp10in2out/Cargo.toml
- programs/psp2in2out-storage/Cargo.toml
- programs/psp2in2out/Cargo.toml
- programs/psp4in4out-app-storage/Cargo.toml
- programs/user-registry/Cargo.toml
- verifier-sdk/Cargo.toml
Bump versions and adjust Github Actions to the new crates.
> chore: Prepare Rust crates for releases

- .github/workflows/light-sdk-tests.yml
- web/webapp/copy-circuits.sh
- web/webapp/copy-env.sh
- web/webapp/package.json
- zk.js/copy-circuits.sh
- add env copy to prebuild step in webapp
- add docker auth to prevent docker hub image pull rate limits
> fix: prebuild env

- zk.js/package.json
- zk.js/src/transaction/solanaTransaction.ts
- zk.js/src/wallet/user.ts
- zk.js/tests/prover.test.ts
- zk.js/tests/system-programs/functional_tests.ts
Changes:
- removed Transaction class from User class
- removed Transaction class from functional tests
> refactor: remove Transaction from User and functional test

- pnpm-lock.yaml
- psp-examples/streaming-payments/tests/streaming-payments.ts
- psp-examples/swap/tests/swaps.ts
- psp-template/psp-template/tests_psp/{{project-name}}.ts
- zk.js/src/transaction/pspTransaction.ts
- zk.js/src/utxo.ts
- zk.js/src/wallet/buildBalance.ts
- zk.js/src/wallet/user.ts
- zk.js/tests/system-programs/functional_tests.ts
Issue:
- for the rpc refactor we need merkle proofs in utxos
Changes:
- added merkle proof to utxo
- added merkle root to shielded transaction type
> refactor(zk.js): add merkle proof to utxo

- zk.js/src/merkle-tree/sol-merkle-tree.ts
- zk.js/src/rpc.ts
- zk.js/src/test-utils/create-random-test-amount.ts
- zk.js/src/test-utils/index.ts
- zk.js/src/test-utils/public-test-rpc.ts
- zk.js/src/test-utils/test-rpc.ts
- zk.js/src/transaction/index-transactions.ts
- zk.js/src/transaction/index.ts
- zk.js/src/utxo/index.ts
- zk.js/src/utxo/parse-utxo.ts
- zk.js/src/utxo/utxo.ts
- zk.js/tests/balance.test.ts
- zk.js/tests/createOutUtxos.test.ts
- zk.js/tests/program-utxo.test.ts
- zk.js/tests/prover.test.ts
- zk.js/tests/rpc.test.ts
- zk.js/tests/selectInUtxos.test.ts
- zk.js/tests/test-utils/compare-utxos.ts
- zk.js/tests/utxo.test.ts
- zk.js/tests/verifiers.test.ts
- fixed zkjs tests 
(open: encryption and 10-in-2-out failing)
- cleanup testrpc/publictestrpc
> chore: swen/feat public testrpc

- merkle-tree/concurrent/src/lib.rs
It's not necessary. Even though spl-concurrent-merkle-tree is doing that, it's really not. The only thing needed for the usual append algorithm to handle the first insertion gracefully is to use 0 as the node index in hash calculations. This is more efficient and less confusing than treating it as an update.
> perf(merkle-tree): Make no distinction between first and other appends

- README.md
minor update to the readme. tho there's still some out-of-date info in the readme, esp. relating to testing
> chore: upd readme

- Cargo.lock
- programs/compressed-pda/Cargo.toml
- programs/compressed-pda/src/lib.rs
- programs/compressed-token/src/process_transfer.rs
- added instruction data serialization for compressed-pda methods
- added tests
- added tlv serialization and test
- token program tlv
- onchain logic and integration tests
> feat: refactored utxo and tlv serialization

- .github/actions/setup-and-build/action.yml
- .github/workflows/js.yml
- .github/workflows/light-sdk-tests.yml
- .github/workflows/light-system-programs-tests.yml
- .github/workflows/lint.yml
- .github/workflows/prover-release.yml
- .github/workflows/prover-test.yml
- .github/workflows/release-macro-circom.yml
- .github/workflows/release-pr.yml
- .github/workflows/release.yml
- .github/workflows/tag.yml
• The checkout action across all workflow files is updated to version 4. 
• Submodules and large file storage (LFS) are enabled in the checkout stage to pull in additional dependencies necessary for each use case.
> chore: update checkout action and enable LFS and submodules

- cli/package.json
- cli/src/commands/balance/index.ts
- cli/test/commands/balance/index.test.ts
- js/compressed-token/tests/e2e/emit-transfer.test.ts
- js/stateless.js/tests/e2e/program.test.ts
Usage:
`  $ light balance --owner <value> --mint <value>`
> feat: add balance command to CLI

- merkle-tree/concurrent/src/lib.rs
- programs/account-compression/src/instructions/nullify_leaves.rs
- programs/account-compression/src/state/address.rs
- programs/account-compression/src/state/change_log_event.rs
- programs/account-compression/tests/address_merkle_tree_tests.rs
- programs/compressed-pda/src/append_state.rs
- programs/compressed-pda/src/compressed_account.rs
- programs/compressed-pda/src/create_address.rs
- programs/compressed-pda/src/instructions.rs
- programs/compressed-pda/src/lib.rs
- programs/compressed-pda/src/nullify_state.rs
- programs/compressed-pda/src/sdk.rs
- programs/compressed-pda/src/verify_state.rs
- programs/compressed-pda/tests/test.rs
- programs/compressed-token/src/process_mint.rs
- programs/compressed-token/src/process_transfer.rs
- programs/package.json
- test-utils/src/test_env.rs
builds on https://github.com/Lightprotocol/light-protocol/pull/547 don't merge before.
Changes:
- check address in compressed pda program
- add logic to create new address
> feat: pda skeleton

- cli/README.md
CLI docs
- comprehensive docs for steps and commands
> chore: update README.md

- .github/workflows/light-system-programs-tests.yml
trigger light-system-programs-tests workflow on circuit-lib/verifier/** changes
> chore: trigger light-system-programs-tests workflow on circuit-lib/verifier/** changes

- merkle-tree/hash-set/src/lib.rs
- merkle-tree/hash-set/src/zero_copy.rs
Make sure all errors are covered:
* `Full` - add new tests.
* `ElementAlreadyExists` - was already tested.
Also, remove error variants which we don't want anymore:
* `Empty` - not used anymore.
> test: Cover all errors in hash set

- js/compressed-token/src/idl/light_compressed_token.ts
- js/stateless.js/src/idls/light_compressed_token.ts
- programs/account-compression/src/processor/initialize_address_queue.rs
- programs/account-compression/src/processor/initialize_concurrent_merkle_tree.rs
- programs/compressed-token/README.md
- programs/compressed-token/src/lib.rs
- programs/compressed-token/src/process_transfer.rs
- programs/compressed-token/src/spl_compression.rs
- programs/compressed-token/src/token_data.rs
- programs/registry/src/lib.rs
- programs/system/Cargo.toml
- programs/system/README.md
- programs/system/src/invoke_cpi/account.rs
- programs/system/src/invoke_cpi/instruction.rs
- programs/system/src/invoke_cpi/process_cpi_context.rs
- programs/system/src/invoke_cpi/verify_signer.rs
- programs/system/src/lib.rs
- programs/system/src/sdk/address.rs
- added minimal readmes to the system and token program
- cleaned up comments/fmt
> chore: program comments formatting

- merkle-tree/concurrent/tests/tests.rs
* Perform a randomized update after each append.
* Perform thousand of updates on the full tree.
* Assert the whole changelog and root buffers.
> test: Improve the tests for zero-copy Merkle tree loader

- cli/src/utils/process.ts
When attempting to stream output to a file, such as using `light test-validator > debug.log`, the following error occurs:
```
light-protocol/node_modules/.pnpm/@oclif+core@3.26.2/node_modules/@oclif/core/lib/command.js:50
throw err;
^
Error [ERR_STREAM_CANNOT_PIPE]: Cannot pipe, not readable
at new NodeError (node:internal/errors:406:5)
at Writable.pipe (node:internal/streams/writable:339:24)
at /Users/tsv/Developer/light-protocol/cli/dist/utils/process.js:52:28
at new Promise (<anonymous>)
at executeCommand (/Users/tsv/Developer/light-protocol/cli/dist/utils/process.js:33:12)
at startTestValidator (/Users/tsv/Developer/light-protocol/cli/dist/utils/initTestEnv.js:162:40) {
code: 'ERR_STREAM_CANNOT_PIPE'
}
```
This PR resolves the ERR_STREAM_CANNOT_PIPE error encountered when streaming …
> fix: cli: allow piping to non-readable streams

- js/compressed-token/src/idl/light_compressed_token.ts
- js/compressed-token/src/instructions/pack-compressed-token-accounts.ts
- js/stateless.js/src/idls/light_compressed_token.ts
- js/stateless.js/src/idls/light_system_program.ts
- programs/compressed-token/src/lib.rs
- programs/compressed-token/src/process_transfer.rs
- programs/system/src/errors.rs
- test-programs/compressed-token-test/tests/test.rs
- test-programs/system-cpi-test/src/lib.rs
- test-utils/src/lib.rs
- test-utils/src/spl.rs
General:
- add failing tests to token program
Changes:
- added DelegateSignerCheckFailed
- add unimplented check for OutputTokenData
- add unimplemtned for signer is delegate
- add failing compression decompression tests
```
/// 1. Invalid decompress account
/// 2. Invalid token pool pda
/// 3. Invalid decompression amount -1
/// 4. Invalid decompression amount +1
/// 5. Invalid decompression amount 0
/// 6. Invalid compression amount -1
/// 7. Invalid compression amount +1
/// 8. Invalid compression amount 0
```
- failing transfer tests (total didn't add all now)
```
/// 1. Invalid token data amount (+ 1)
/// 2. Invalid token data amount (- 1)
/// 3. Invalid token data zero out amount
/// 4. Invalid double token data amount
/// 5. Invalid input token data amount (0)
/// 6. Invalid …
```
> test: token program

- programs/compressed-token/src/process_mint.rs
- programs/system/src/invoke/verify_state_proof.rs
- programs/system/src/sdk/address.rs
- programs/system/src/sdk/compressed_account.rs
- programs/system/src/sdk/event.rs
- programs/system/src/sdk/invoke.rs
- test-programs/account-compression-test/tests/group_authority_tests.rs
- test-programs/registry-test/tests/tests.rs
- test-programs/system-cpi-test/tests/test_program_owned_trees.rs
- test-programs/system-test/tests/test.rs
- test-utils/src/e2e_test_env.rs
- utils/src/lib.rs
remove truncate_to_circuit and change_endianness, add unit tests fo address.rs fns (add_and_get_remaining_account_indices,derive_address
> chore: add unit tests for address.rs

- .github/workflows/light-system-programs-tests.yml
- programs/compressed-token/src/process_transfer.rs
- programs/compressed-token/src/token_data.rs
- programs/system/Cargo.toml
- programs/system/src/invoke_cpi/processor.rs
chore(compressed-token): add sum failing test
> chore: feature gate cpi context

- merkle-tree/hash-set/src/lib.rs
Restore the `HashSetIterator` and `HashSet::iter()`, but this time make sure that it works properly.
> fix: Hash set iterator

- test-programs/account-compression-test/tests/address_merkle_tree_tests.rs
- test-programs/account-compression-test/tests/merkle_tree_tests.rs
Trying to initialize trees and queues on top of accounts smaller than expected should result in `ConcurrentMerkleTreeError::BufferSize`.
> test: Initializing Merkle tree and queue accounts with invalid sizes

- .github/workflows/light-sdk-tests.yml
- circuit-lib/circuit-lib.js/package.json
- cli/package.json
- cli/src/utils/process.ts
- hasher.rs/package.json
- light-prover/README.md
- light-prover/bench.sh
- light-prover/integration_test.go
- light-prover/main.go
- light-prover/merkle-tree/test_tree.go
- light-prover/merkle-tree/tree_test.go
- light-prover/prover/circuit_builder.go
- light-prover/prover/circuit_utils.go
- light-prover/prover/combined_circuit.go
- light-prover/prover/combined_proving_system.go
- light-prover/prover/combined_test.go
- light-prover/prover/extractor.go
- light-prover/prover/inclusion_circuit.go
- light-prover/prover/inclusion_proving_system.go
- light-prover/prover/inclusion_test.go
- light-prover/prover/marshal.go
- light-prover/prover/marshal_inclusion.go
- light-prover/prover/marshal_non_inclusion.go
- light-prover/prover/non_inclusion_circuit.go
- light-prover/prover/non_inclusion_proving_system.go
- light-prover/prover/non_inclusion_test.go
- light-prover/scripts/generate_keys.sh
- light-prover/server/server.go
- nx.json
should be merged after https://github.com/Lightprotocol/light-protocol/pull/841
Changes:
- replace all ocurrences of utxo with compressed account in light prover
> chore: light prover cleanup

- merkle-tree/indexed/tests/tests.rs
When the indexed changelog wraps around and an actor tries to perform an update with a proof from before that happened, we expect an error (`CannotUpdateLeaf`).
> test: Add a wrap-around test case for address Merkle tree concurrency

- js/compressed-token/src/idl/light_compressed_token.ts
- js/stateless.js/src/idls/light_compressed_token.ts
- merkle-tree/indexed/src/lib.rs
- pnpm-lock.yaml
- programs/account-compression/src/errors.rs
- programs/account-compression/src/instructions/update_address_merkle_tree.rs
- programs/account-compression/src/processor/initialize_address_queue.rs
- programs/account-compression/src/processor/initialize_concurrent_merkle_tree.rs
- test-utils/src/address_tree_rollover.rs
- test-utils/src/assert_address_merkle_tree.rs
- test-utils/src/test_env.rs
Changes:
- assert size in rollover
- add check rollover fee sanity check onchain
> chore: add some  merkle tree asserts

- Cargo.lock
- merkle-tree/bounded-vec/src/lib.rs
> chore: remove clone from

- merkle-tree/hash-set/src/lib.rs
* `next_value_index` doesn't exist in `HashSet` anymore.
* Stick to the naming prsent in `HashSet`, therefore rename `values` to `buckets`.
> fix: Don't initialize the non-existent `next_value_index` in `copy_from_bytes`

- programs/account-compression/src/instructions/deregister_program.rs
- programs/account-compression/src/instructions/mod.rs
- programs/account-compression/src/lib.rs
- test-programs/account-compression-test/tests/group_authority_tests.rs
Changes:
- add deregister program instruction
> feat: add deregister program

- cli/src/commands/balance/index.ts
- js/compressed-token/src/actions/compress.ts
- js/compressed-token/src/actions/create-token-program-lookup-table.ts
- js/compressed-token/src/actions/index.ts
- js/compressed-token/src/actions/mint-to.ts
- js/compressed-token/src/program.ts
- js/compressed-token/tests/e2e/compress.test.ts
- js/compressed-token/tests/e2e/mint-to.test.ts
- js/stateless.js/src/rpc.ts
- js/stateless.js/src/utils/send-and-confirm.ts
review / merge this after #1072 please
> feat: lookuptable support + batch compress 

- examples/browser/nextjs/src/app/page.tsx
> fix: update page.tsx to use `accounts.items` for selectMinCompressedSolAccountsForTransfer

- Cargo.lock
- Cargo.toml
- macros/aligned-sized/Cargo.toml
- macros/light/Cargo.toml
- macros/light/src/accounts.rs
- macros/light/src/hasher.rs
- macros/light/src/traits.rs
Also, move all macro-related dependencies to the workspace.
> chore: Update syn to 2.0

- cli/package.json
- js/compressed-token/src/idl/light_compressed_token.ts
- js/stateless.js/src/idls/account_compression.ts
- js/stateless.js/src/idls/light_compressed_token.ts
- js/stateless.js/src/idls/light_registry.ts
- js/stateless.js/src/idls/light_system_program.ts
- scripts/release-all-rust-crates.sh
released crates and cli based on: #1124
> chore: released rust crates and cli with patched agave client

- cli/src/commands/test-validator/index.ts
- cli/src/utils/initTestEnv.ts
- cli/src/utils/processPhotonIndexer.ts
- cli/test/commands/config/index.test.ts
- js/compressed-token/src/idl/light_compressed_token.ts
- js/stateless.js/src/idls/light_compressed_token.ts
- scripts/install.sh
make it easy for users to stop the test-validator and related background processes
> feat: add test-validator --stop flag

- programs/account-compression/src/errors.rs
- programs/account-compression/src/instructions/nullify_leaves.rs
> chore: add proof len consistency check

- programs/system/src/invoke/processor.rs
- implements suggestion os-lpl-sug-04-04
> refactor: use existing variable for vec len

- forester/src/send_transaction.rs
Refactored the code to fetch address and state proofs concurrently for improved performance.
> feat: forester: fetch proofs in parallel 

- light-prover/README.md
This new section credits the Semaphore Merkle Tree Batcher (SMTB) by Worldcoin as the basis for this project. 
It guides interested users to the original SMTB repository for further reference.
> chore: Add acknowledgment section to light-prover README

- js/stateless.js/src/rpc.ts
Introduced a debug flag to RPC function, allowing developers to print stack traces and generate cURL commands for easier troubleshooting.
> feat: add debugging capability to RPC function

- forester/alert_rules.yml
- forester/alertmanager.yml
- forester/src/epoch_manager.rs
- forester/src/metrics.rs
Implemented periodic SOL balance checks and updated metrics to include SOL balance.
> feat: forester: Add SOL balance monitoring and alerting

- cli/package.json
- cli/src/utils/process.ts
- pnpm-lock.yaml
Reported by CodeQL[0].
[0] https://github.com/Lightprotocol/light-protocol/security/code-scanning/1
> fix: Construct the shell command for killing processes safely

- photon-api/src/models/compressed_proof.rs
See also: https://discord.com/channels/892771619687268383/997475867674546198/1291084593033777304
> fix: photon api: deserialization of CompressedProof

- README.md
Changes:
- add missing requirements to readme
- taken from [config.toml comments](https://github.com/Lightprotocol/light-protocol/blob/main/.cargo/config.toml#L4-L30)
> chore: add missing install reqirement

- Cargo.lock
- circuit-lib/light-prover-client/Cargo.toml
- circuit-lib/light-prover-client/scripts/prover.sh
- circuit-lib/light-prover-client/src/batch_append.rs
- circuit-lib/light-prover-client/src/batch_update.rs
- circuit-lib/light-prover-client/src/gnark/batch_append_json_formatter.rs
- circuit-lib/light-prover-client/src/gnark/helpers.rs
- circuit-lib/light-prover-client/tests/gnark.rs
- light-prover/integration_test.go
- light-prover/main.go
- light-prover/prover/batch_append_circuit.go
- light-prover/prover/batch_update_circuit.go
- light-prover/prover/circuit_builder.go
- light-prover/prover/marshal_append.go
- light-prover/prover/marshal_update.go
- light-prover/prover/test_data_helpers.go
- merkle-tree/reference/src/lib.rs
- merkle-tree/reference/src/sparse_merkle_tree.rs
Changes:
- add tests for `light-prover-client` batch update and append
> fix: add light prover client batch update and append tests

- light-prover/scripts/download_keys.sh
Fix for https://github.com/Lightprotocol/light-protocol/issues/1385
> fix: simplify file download logic in download_keys.sh

- cli/package.json
- cli/src/commands/test-validator/index.ts
- cli/src/utils/initTestEnv.ts
- examples/browser/nextjs/tsconfig.json
> feat: add --geyser-config and --validator-args CLI flags

- js/compressed-token/package.json
- js/compressed-token/src/actions/create-mint.ts
- js/compressed-token/src/idl/light_compressed_token.ts
- js/compressed-token/src/program.ts
- js/stateless.js/package.json
- js/stateless.js/src/idls/light_compressed_token.ts
- scripts/install.sh
- allow mintSize to be passed to createMint instruction. this is required if users want to createMint with t22 extensions
- release js 0.17.0
> chore: JS release t22

- client/src/transaction_params.rs
- js/compressed-token/src/idl/light_compressed_token.ts
- js/stateless.js/src/idls/light_compressed_token.ts
- programs/compressed-token/src/burn.rs
- programs/compressed-token/src/process_transfer.rs
- test-utils/src/spl.rs
Changes:
- fix typo `additonal` -> `additional` in multiple files
> chore: fix additonal typo

- js/compressed-token/src/idl/light_compressed_token.ts
- js/stateless.js/src/idls/light_compressed_token.ts
- programs/compressed-token/src/spl_compression.rs
**Changes:**
1. unify `is_valid_token_pool_pda` in compress spl tokens
2. fix comments in `invoke_token_program_with_multiple_token_pool_accounts`
> chore: unify is_valid_token_pool_pda in compress spl tokens

- cli/README.md
This pull request addresses a minor typo in the `README.md` file to enhance the clarity and professionalism of the documentation.
- Corrected the spelling of "prerequesites" to "prerequisites."
---
This change ensures that the documentation maintains high-quality standards and improves readability for developers setting up the CLI.
> Fix typo Update README.md

- program-libs/account-checks/src/checks.rs
- program-libs/batched-merkle-tree/src/constants.rs
- program-libs/batched-merkle-tree/src/initialize_state_tree.rs
- program-libs/batched-merkle-tree/src/merkle_tree.rs
- program-libs/batched-merkle-tree/src/queue.rs
- program-libs/compressed-account/src/lib.rs
- program-libs/merkle-tree-metadata/src/lib.rs
builds on https://github.com/Lightprotocol/light-protocol/pull/1669
> chore: unify queue and tree types

- .github/workflows/rust.yml
- program-libs/compressed-account/Cargo.toml
- program-libs/zero-copy/Cargo.toml
- program-libs/zero-copy/README.md
- program-libs/zero-copy/src/cyclic_vec.rs
- program-libs/zero-copy/src/slice.rs
- program-libs/zero-copy/src/slice_mut.rs
- program-libs/zero-copy/src/vec.rs
- program-libs/zero-copy/tests/cyclic_vec_tests.rs
- program-libs/zero-copy/tests/slice_mut_test.rs
- program-libs/zero-copy/tests/slice_test.rs
- program-libs/zero-copy/tests/vec_tests.rs
Changes:
1. make std non default
2. feature gate try_into_array, to_vec behind std feature
3. tests are std based -> adapt github workflow to use std feature for tests
> chore: remove std feature as default

- cli/src/commands/init/index.ts
conjuction - conjunction `fix typo`
> fix error index.ts
